Repository antinomyhq/forge, pull requests merged in 2025-08, with the labels that each got.

#1315 fix: add HTTP/2 support and improve error handling in ForgeHttpInfra
  Cargo.lock
  Cargo.toml
  README.md
  crates/forge_domain/src/http_config.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/http.rs
Labels: type: fix

#1310 fix: handle file names with special chars in fuzzy matcher
  crates/forge_main/src/completer/input_completer.rs
Labels: type: chore, type: fix

#1323 fix: add label for switching model in banner display
  crates/forge_main/src/banner.rs
Labels: type: fix

#1329 fix: remove instructions that were not helping
  templates/forge-system-prompt-engineer-act.hbs
Labels: type: fix

#1325 chore: add tests for orchestrator
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/lib.rs
  crates/forge_app/tests/orch_spec.rs
  crates/forge_app/tests/orchestrator_test_helpers.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/http_config.rs
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_mixed_content_with_images.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_multiple_images_single_tool_result.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_multiple_tool_results_with_images.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_no_tool_results.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_preserves_error_flag.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_single_image.snap
  crates/forge_domain/src/snapshots/forge_domain__context__tests__update_image_tool_calls_tool_results_no_images.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__drop_reasoning_details__tests__drop_reasoning_details_mixed_message_types.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__drop_reasoning_details__tests__drop_reasoning_details_preserves_non_text_messages.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__drop_reasoning_details__tests__drop_reasoning_details_preserves_other_fields.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__drop_reasoning_details__tests__drop_reasoning_details_removes_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__image_handling__tests__image_handling_mixed_content_with_images.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__image_handling__tests__image_handling_multiple_images_in_single_tool_result.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__image_handling__tests__image_handling_preserves_error_flag.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__image_handling__tests__image_handling_preserves_non_tool_messages.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__image_handling__tests__image_handling_single_image.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_when_no_assistant_message_present.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__set_model__tests__set_model_for_user_messages.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__set_model__tests__set_model_only_affects_user_messages.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__set_model__tests__set_model_preserves_existing_models.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__tests__transformer_pipe.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__transform_tool_calls__tests__transform_tool_calls_converts_tool_results_to_user_messages.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__transform_tool_calls__tests__transform_tool_calls_removes_tool_calls_from_assistant.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__transform_tool_calls__tests__transform_tool_calls_with_model.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_server_error.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_success.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__assistant_message_with_tool_call_conversion.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__message_with_special_chars.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_conversion.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_typescript_code.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_with_special_chars.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__user_message_conversion.snap
  templates/forge-partial-system-info.hbs
Labels: type: chore

#1203 fix: improve tool truncation performance
  README.md
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_max_output.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_min_lines_but_max_line_length.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_output.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_very_lengthy_one_line_match.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_with_results.snap
  crates/forge_app/src/tool_executor.rs
  crates/forge_app/src/truncation.rs
  crates/forge_app/src/truncation/mod.rs
  crates/forge_app/src/truncation/truncate_fetch.rs
  crates/forge_app/src/truncation/truncate_search.rs
  crates/forge_app/src/truncation/truncate_shell.rs
  crates/forge_app/tests/orchestrator_test_helpers.rs
  crates/forge_domain/src/env.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_main/src/info.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/attachment.rs
  forge.yaml
Labels: type: fix

#1340 fix: update line truncation to handle character count and add unicode tests
  crates/forge_app/src/truncation/truncate_shell.rs
Labels: type: fix

#1341 fix: update workflow configuration and enhance template guidelines
  crates/forge_app/tests/orch_spec.rs
  crates/forge_app/tests/snapshots/orch_spec__system_prompt.snap
  crates/forge_app/tests/snapshots/orch_spec__system_prompt_tool_supported.snap
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/workflow.rs
  templates/forge-custom-agent-template.hbs
  templates/forge-system-prompt-engineer-act.hbs
Labels: type: fix

#1345 feat: parse line start end symbol in attachment
  crates/forge_domain/src/attachment.rs
  crates/forge_services/src/attachment.rs
  forge.yaml
Labels: type: feature

#1358 fix: add cache hydration in new conversation handling
  crates/forge_main/src/ui.rs
Labels: type: fix

#1371 feat: forge sandbox
  crates/forge_main/src/cli.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/sandbox.rs
  crates/forge_main/src/ui.rs
  forge.yaml
Labels: type: feature

#1372 fix: context limit being exceeded with image URLs
  crates/forge_domain/src/context.rs
Labels: type: fix

#1377 fix: system lag on exit
  crates/forge_tracker/Cargo.toml
  crates/forge_tracker/src/dispatch.rs
  crates/forge_tracker/src/event.rs
Labels: type: fix

#1382 fix: summarization prompt improvements
  templates/forge-system-prompt-context-summarizer.hbs
  templates/forge-system-prompt-engineer-plan.hbs
Labels: type: fix

#1293 feat: Added configurable timeout for tools (#1249)
  README.md
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/orch_spec/orch_setup.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_main/src/info.rs
  crates/forge_services/src/attachment.rs
Labels: type: feature

#1384 fix: removed dead code
  crates/forge_domain/src/tool_usage.rs
Labels: type: fix

#1390 fix: split compaction handling into system and user message
  crates/forge_app/src/compact.rs
  templates/forge-system-prompt-context-summarizer.hbs
Labels: type: fix

#1385 chore: treat policy denial as success response
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/policies/config.rs
  crates/forge_domain/src/policies/engine.rs
  crates/forge_domain/src/policies/operation.rs
  crates/forge_domain/src/policies/policy.rs
  crates/forge_domain/src/policies/rule.rs
  crates/forge_domain/src/tools.rs
  crates/forge_services/src/permissions.default.yaml
  crates/forge_services/src/policy.rs
Labels: type: chore

#1394 fix: windows file attachments
  crates/forge_domain/src/attachment.rs
Labels: type: fix

#1397 feat: add new agents for documentation review and technical writing
  forge.default.yaml
  templates/forge-system-prompt-parker-code-review.hbs
  templates/forge-system-prompt-prime-review.hbs
Labels: type: feature

#1401 fix: update permissions to allow all read, write, command, and url access
  crates/forge_services/src/permissions.default.yaml
Labels: type: fix

#1417 fix: disable login call on start and update provider error message.
  crates/forge_main/src/ui.rs
  crates/forge_services/src/provider/registry.rs
Labels: type: fix

#1414 fix: ensure tool_choice is set only when tools are defined in the req
  crates/forge_app/src/dto/openai/transformers/tool_choice.rs
Labels: type: fix

#1412 fix: prevent overflow in eviction logic for empty or single message context
  crates/forge_domain/src/compaction_strategy.rs
Labels: type: fix

#1418 fix: update README for clarity and organization of setup instructions
  README.md
Labels: type: fix

#1419 fix: update active_plan placeholder to specify absolute path of the plan file
  templates/forge-system-prompt-context-summarizer.hbs
Labels: type: fix

#1411 fix: refactor tool call arguments handling to use ToolCallArguments type
  crates/forge_app/src/dto/openai/request.rs
  crates/forge_app/src/dto/openai/transformers/drop_tool_call.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_spec.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/compaction_strategy.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/result_stream_ext.rs
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_deser_failure.snap
  crates/forge_domain/src/tool_call.rs
  crates/forge_domain/src/tool_call_args.rs
  crates/forge_domain/src/tool_call_parser.rs
  crates/forge_domain/src/tools.rs
  crates/forge_domain/src/transformer/mod.rs
  crates/forge_domain/src/transformer/transform_tool_calls.rs
  crates/forge_json_repair/src/lib.rs
  crates/forge_json_repair/src/parser.rs
  crates/forge_json_repair/tests/comments_unicode.rs
  crates/forge_json_repair/tests/complex_repairs.rs
  crates/forge_json_repair/tests/error_cases.rs
  crates/forge_json_repair/tests/escaping.rs
  crates/forge_json_repair/tests/numbers.rs
  crates/forge_json_repair/tests/punctuation.rs
  crates/forge_json_repair/tests/quotes.rs
  crates/forge_json_repair/tests/special_quotes.rs
  crates/forge_json_repair/tests/special_values.rs
  crates/forge_json_repair/tests/strings.rs
  crates/forge_json_repair/tests/truncation.rs
  crates/forge_json_repair/tests/valid_json.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/provider/anthropic.rs
Labels: type: chore, type: fix

#1301 feat: Open new chat on completion
  crates/forge_app/src/agent_executor.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/mcp_executor.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_spec.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/session_metrics.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tools.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/ui.rs
  crates/forge_main_neo/src/widgets/message_list.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/tool_services/fs_remove.rs
Labels: type: feature, ratatui

#1429 chore: drop task management tools
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/fmt/fmt_task.rs
  crates/forge_app/src/fmt/mod.rs
  crates/forge_app/src/fmt/snapshots/forge_app__fmt__fmt_task__tests__all_done_tasks_markdown_snapshot.snap
  crates/forge_app/src/fmt/snapshots/forge_app__fmt__fmt_task__tests__complex_task_list_markdown_snapshot.snap
  crates/forge_app/src/fmt/snapshots/forge_app__fmt__fmt_task__tests__empty_task_list_markdown_snapshot.snap
  crates/forge_app/src/fmt/snapshots/forge_app__fmt__fmt_task__tests__mixed_status_tasks_markdown_snapshot.snap
  crates/forge_app/src/fmt/snapshots/forge_app__fmt__fmt_task__tests__single_pending_task_markdown_snapshot.snap
  crates/forge_app/src/operation.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_append_operation.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_complex_scenario.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_empty.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_large_numbers.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_mark_done_operation.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_mixed_status_tasks.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__task_list_single_pending_task.snap
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/task.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tools.rs
Labels: type: chore, ratatui

#1428 fix: improve agent-2-agent communication via tool call
  crates/forge_app/src/agent.rs
  crates/forge_app/src/agent_executor.rs
  crates/forge_app/src/fmt/content.rs
  crates/forge_app/src/mcp_executor.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_runner.rs
  crates/forge_app/src/orch_spec/orch_spec.rs
  crates/forge_app/src/orch_spec/snapshots/forge_app__orch_spec__orch_system_spec__system_prompt.snap
  crates/forge_app/src/tool_executor.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tools.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/ui.rs
  crates/forge_main_neo/src/domain/update.rs
  crates/forge_main_neo/src/widgets/message_list.rs
Labels: type: feature, type: fix, ratatui

#1431 fix: drop forced login for users
  crates/forge_main/src/ui.rs
Labels: type: fix

#1432 fix: improve format for reasoning messages
  crates/forge_main/src/ui.rs
Labels: type: fix

#1422 fix: agent level custom rules not getting attached when default custom rules are defined
  crates/forge_domain/src/conversation.rs
Labels: type: fix

#1441 fix: improve system prompt caching
  crates/forge_app/src/dto/openai/transformers/set_cache.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_setup.rs
  crates/forge_app/src/orch_spec/orch_system_spec.rs
  crates/forge_app/src/orch_spec/snapshots/forge_app__orch_spec__orch_system_spec__system_prompt.snap
  crates/forge_app/src/orch_spec/snapshots/forge_app__orch_spec__orch_system_spec__system_prompt_tool_supported.snap
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/system_context.rs
  templates/forge-custom-agent-template.hbs
Labels: type: feature, type: fix

#1439 fix: implement `set-cache` transformer and usage for Anthropic
  crates/forge_app/src/dto/anthropic/request.rs
  crates/forge_app/src/dto/anthropic/response.rs
  crates/forge_app/src/dto/anthropic/transforms/mod.rs
  crates/forge_app/src/dto/anthropic/transforms/set_cache.rs
  crates/forge_app/src/dto/openai/transformers/set_cache.rs
  crates/forge_app/src/dto/openai/transformers/tool_choice.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_services/src/provider/anthropic.rs
  crates/forge_services/src/provider/snapshots/forge_services__provider__anthropic__tests__request_conversion.snap
Labels: type: fix

#1415 chore: clean up posthog implementation
  Cargo.lock
  crates/forge_tracker/Cargo.toml
  crates/forge_tracker/src/log.rs
Labels: type: chore

#1446 feat: add Cerebras provider support
  README.md
  crates/forge_app/src/dto/openai/transformers/make_cerebras_compat.rs
  crates/forge_app/src/dto/openai/transformers/mod.rs
  crates/forge_app/src/dto/openai/transformers/pipeline.rs
  crates/forge_domain/src/provider.rs
  crates/forge_services/src/provider/registry.rs
Labels: type: feature

#1448 feat: show usage on completion
  crates/forge_main/src/info.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#1465 fix: sync conversation before completion
  crates/forge_app/src/orch.rs
Labels: type: fix
