Repository antinomyhq/forge, pull requests merged in 2025-09, with the labels that each got.

#1478 feat: add `/sage` command
  .devcontainer/devcontainer.json
  crates/forge_domain/src/agent.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_main_neo/src/domain/slash_command.rs
  crates/forge_main_neo/src/domain/update_key_event.rs
Labels: type: feature, ratatui

#1481 chore: simplify forge.yaml
  AGENTS.md
  forge.yaml
Labels: type: chore

#1482 chore: rename templates from .hbs to .md
  crates/forge_app/src/compact.rs
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_inte/tests/test_workflow.rs
  crates/forge_services/src/template.rs
  forge.default.yaml
  templates/forge-custom-agent-template.md
  templates/forge-partial-summary-frame.md
  templates/forge-partial-system-info.md
  templates/forge-partial-tool-error-reflection.md
  templates/forge-partial-tool-required.md
  templates/forge-partial-tool-use-example.md
  templates/forge-system-prompt-context-summarizer.md
  templates/forge-system-prompt-engineer-act.md
  templates/forge-system-prompt-engineer-plan.md
  templates/forge-system-prompt-parker-code-review.md
  templates/forge-system-prompt-prime-review.md
  templates/forge-system-prompt-sage-research.md
Labels: type: chore

#1483 refactor: drop agents from workflow
  AGENTS.md
  Cargo.lock
  Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/agent.rs
  crates/forge_app/src/agent_executor.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_runner.rs
  crates/forge_app/src/orch_spec/orch_setup.rs
  crates/forge_app/src/orch_spec/snapshots/forge_app__orch_spec__orch_system_spec__system_prompt.snap
  crates/forge_app/src/orch_spec/snapshots/forge_app__orch_spec__orch_system_spec__system_prompt_tool_supported.snap
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/workflow_manager.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/merge.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_inte/Cargo.toml
  crates/forge_inte/fixtures/juniper.md
  crates/forge_inte/tests/api_spec.rs
  crates/forge_inte/tests/test_workflow.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/agent_loader.rs
  crates/forge_services/src/agents/forge.md
  crates/forge_services/src/agents/muse.md
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
  crates/forge_services/src/agents/sage.md
  crates/forge_services/src/conversation.rs
  forge.default.yaml
  forge.schema.json
  forge.yaml
Labels: type: chore

#1487 fix: update tool description for file read operations
  .devcontainer/devcontainer.json
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tools.rs
  crates/forge_services/src/tool_services/fs_read.rs
Labels: type: docs, type: fix

#1491 fix: adjust indentation for item display in Info struct
  crates/forge_main/src/info.rs
Labels: type: fix

#1490 fix: add HTTP status code `408` to retry status codes
  .github/workflows/ci.yml
  Cargo.lock
  crates/forge_ci/src/workflows/ci.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
  forge.yaml
Labels: type: fix

#1494 fix: prevent overwriting existing agent models
  crates/forge_domain/src/conversation.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#1496 fix: update interaction guidelines and streamline shell command execution instructions
  templates/forge-system-prompt-engineer-act.md
Labels: type: fix

#1497 fix: remove fixed models from built-in agents
  crates/forge_services/src/agents/forge.md
  crates/forge_services/src/agents/muse.md
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
  crates/forge_services/src/agents/sage.md
Labels: type: docs, type: fix

#1498 fix: update built-in agent prompt
  crates/forge_services/src/agents/forge.md
  crates/forge_services/src/agents/muse.md
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
  crates/forge_services/src/agents/sage.md
  templates/forge-system-prompt-engineer-act.md
  templates/forge-system-prompt-engineer-plan.md
  templates/forge-system-prompt-parker-code-review.md
  templates/forge-system-prompt-prime-review.md
  templates/forge-system-prompt-sage-research.md
Labels: type: fix

#1499 feat: enhance agent switch message to include title if available
  crates/forge_main/src/ui.rs
  crates/forge_services/src/agents/forge.md
  crates/forge_services/src/agents/muse.md
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
  crates/forge_services/src/agents/sage.md
Labels: type: feature

#1500 feat: add support for providing env variables for shell execution
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tools.rs
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/custom_instructions.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tool_services/shell.rs
  plans/2025-09-07-shell-env-variable-support-v1.md
Labels: type: feature

#1502 chore: add workflow for closing stale issues and PRs
  .github/workflows/stale.yml
  crates/forge_ci/src/workflows/mod.rs
  crates/forge_ci/src/workflows/stale.rs
  crates/forge_ci/tests/ci.rs
Labels: type: feature, type: chore

#1503 chore: drop `gh-workflow-tailcall` and use `gh-workflow` directly
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  Cargo.lock
  Cargo.toml
  crates/forge_ci/Cargo.toml
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/jobs/draft_release_update_job.rs
  crates/forge_ci/src/jobs/label_sync_job.rs
  crates/forge_ci/src/jobs/release_build_job.rs
  crates/forge_ci/src/jobs/release_draft.rs
  crates/forge_ci/src/jobs/release_homebrew.rs
  crates/forge_ci/src/jobs/release_npm.rs
  crates/forge_ci/src/workflows/ci.rs
  crates/forge_ci/src/workflows/labels.rs
  crates/forge_ci/src/workflows/release_drafter.rs
  crates/forge_ci/src/workflows/release_publish.rs
  crates/forge_ci/src/workflows/stale.rs
Labels: type: fix

#1501 fix: send reasoning settings to upstream
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/context.rs
Labels: type: fix

#1508 feat: support for STDIN
  Cargo.lock
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/main.rs
  zsh-plugin/forge.plugin.zsh
Labels: type: feature

#1509 feat: add line number in fs_read output
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tools.rs
Labels: type: feature

#1540 feat: add line numbering to file content in attachments
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/line_numbers.rs
  crates/forge_services/src/attachment.rs
Labels: type: feature

#1546 chore: add draft release job for pull requests for build all targets
  .github/workflows/ci.yml
  crates/forge_app/src/app.rs
  crates/forge_ci/src/jobs/mod.rs
  crates/forge_ci/src/jobs/release_draft_pr.rs
  crates/forge_ci/src/workflows/ci.rs
  crates/forge_domain/src/agent.rs
Labels: type: chore, ci: build all targets

#1545 fix: show attempt-completion in `/tools` for all agents
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_setup.rs
  crates/forge_services/src/agent_loader.rs
Labels: type: fix

#1529 fix: show actual error instead of simple message
  crates/forge_infra/src/http.rs
  crates/forge_services/src/provider/openai.rs
  crates/forge_services/src/provider/snapshots/forge_services__provider__openai__tests__detailed_error_message_included.snap
Labels: type: fix

#1547 feat: insert `/agent-<agent-name>` aliases
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  plans/2025-09-13-dynamic-agent-slash-commands-v3.md
Labels: type: feature

#1543 fix: add `libsqlite3-sys` dependency to Cargo.toml and Cargo.lock
  .github/workflows/ci.yml
  Cargo.lock
  crates/forge_ci/src/jobs/mod.rs
  crates/forge_ci/src/jobs/release_draft_pr.rs
  crates/forge_ci/src/workflows/ci.rs
  crates/forge_infra/Cargo.toml
Labels: type: fix, ci: build all targets

#1548 feat: add `FORGE_HISTORY_FILE` env variable
  README.md
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/orch_spec/orch_setup.rs
  crates/forge_domain/src/env.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_main/src/info.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/tool_services/shell.rs
  plans/2025-09-13-forge-history-file-env-var-v2.md
Labels: type: feature

#1560 fix: user prompt format
  crates/forge_services/src/agents/forge.md
  crates/forge_services/src/agents/muse.md
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
  crates/forge_services/src/agents/sage.md
Labels: type: fix

#1565 fix: performance improvements for compaction
  crates/forge_app/src/compact.rs
  templates/forge-system-prompt-context-summarizer.md
Labels: type: performance, ci: benchmark, type: fix

#1554 feat: show conversation id in `/info`
  crates/forge_main/src/info.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#1569 fix: don't exit on an invalid command
  crates/forge_main/src/ui.rs
Labels: type: fix

#1570 fix: unexpected tool call failure limits being hit
  crates/forge_app/src/orch.rs
  crates/forge_app/src/orch_spec/orch_spec.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#1573 fix: refine wording in research question handling instructions
  crates/forge_services/src/agents/sage.md
Labels: type: fix

#1574 fix: load usage from conversation
  crates/forge_main/src/conversation_selector.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#1581 fix: minor ZSH plugin improvements
  crates/forge_main/src/info.rs
  crates/forge_main/src/ui.rs
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1591 chore: improve ZSH compatibility
  crates/forge_main/src/cli.rs
  crates/forge_main/src/completer/command.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  shell-plugin/forge.plugin.zsh
Labels: type: chore

#1599 fix: sort tools by name
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/transformer/mod.rs
  crates/forge_domain/src/transformer/sort_tools.rs
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1601 fix(zsh): handle `CTRL+C` better
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1600 fix(zsh): unset user action
  crates/forge_main/src/ui.rs
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1604 fix: many fixes
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1608 fix: add only files in system prompt
  crates/forge_app/src/app.rs
Labels: type: fix

#1609 refactor: drop prime and parker
  crates/forge_services/src/agent_loader.rs
  crates/forge_services/src/agents/parker.md
  crates/forge_services/src/agents/prime.md
Labels: type: chore

#1613 fix(zsh): empty prompts will set the agent
  shell-plugin/forge.plugin.zsh
Labels: type: fix
