Repository antinomyhq/forge, pull requests merged in 2025-10, with the labels that each got.

#1638 chore: update action trigger
  .github/workflows/release-drafter.yml
  crates/forge_ci/src/workflows/release_drafter.rs
Labels: type: chore

#1623 feat: implement configuration management commands
  AGENTS.md
  Cargo.lock
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/cli_format.rs
  crates/forge_main/src/config/display.rs
  crates/forge_main/src/config/error.rs
  crates/forge_main/src/config/handler.rs
  crates/forge_main/src/config/mod.rs
  crates/forge_main/src/env.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  shell-plugin/forge.plugin.zsh
Labels: type: feature

#1645 fix: raise an error if no provider is configured.
  crates/forge_main/src/ui.rs
Labels: type: fix

#1643 feat: add session management commands for handling conversations
  crates/forge_main/src/banner.rs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/cli_format.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/ui.rs
  shell-plugin/README.md
  shell-plugin/forge.plugin.zsh
Labels: type: feature

#1650 refactor: move model configuration into a JSON file
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/dto/app_config.rs
  crates/forge_app/src/dto/provider.rs
  crates/forge_infra/src/database/repository/app_config.rs
  crates/forge_infra/src/env.rs
  crates/forge_services/src/provider/models.json
  crates/forge_services/src/provider/registry.rs
Labels: type: chore

#1653 fix: correct command references from "/conversations" to "/conversation"
  crates/forge_main/src/banner.rs
  crates/forge_main/src/model.rs
Labels: type: fix

#1651 feat: add 'show-tools' command and update zsh plugin
  Cargo.lock
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/env.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  shell-plugin/forge.plugin.zsh
Labels: type: feature

#1658 feat: add BigModel provider
  crates/forge_app/src/dto/provider.rs
  crates/forge_services/src/provider/provider.json
Labels: type: feature

#1659 fix: empty app config
  crates/forge_infra/src/database/repository/app_config.rs
Labels: type: fix

#1662 fix: order of conversation by `updated_at`
  crates/forge_infra/src/database/repository/conversation.rs
Labels: type: fix

#1663 fix: tool validation to support glob patterns
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/tool_resolver.rs
Labels: type: fix

#1660 fix: improve ZSH experience
  Cargo.lock
  Cargo.toml
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/inquire.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/conversation_selector.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/select.rs
  crates/forge_main/src/ui.rs
  crates/forge_main/src/update.rs
  crates/forge_select/Cargo.toml
  crates/forge_select/README.md
  crates/forge_select/src/lib.rs
  crates/forge_select/src/select.rs
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1667 fix: add reasoning configuration and styles to conversation rendering
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/conversation_style.css
Labels: type: fix

#1673 feat: add Z.ai thinking transformation
  crates/forge_app/src/dto/openai/request.rs
  crates/forge_app/src/dto/openai/transformers/mod.rs
  crates/forge_app/src/dto/openai/transformers/pipeline.rs
  crates/forge_app/src/dto/openai/transformers/zai_reasoning.rs
Labels: type: feature

#1672 fix: revert `FORGE_BIN` to default 'forge' for consistency
  shell-plugin/forge.plugin.zsh
Labels: type: fix

#1677 fix: agent ID retrieval in tools command
  crates/forge_main/src/ui.rs
Labels: type: fix

#1678 fix: remove unnecessary search output from CLI
  crates/forge_app/src/fmt/fmt_output.rs
Labels: type: fix
