Repository antinomyhq/forge, pull requests merged in 2025-05, with the labels that each got.

#731 fix(tracker): track toolcall usage
  crates/forge_main/src/ui.rs
  crates/forge_tracker/src/event.rs
  crates/forge_tracker/src/lib.rs
Labels: type: feature

#729 feat(workflow): implement config file search in parent directories
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/services.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/workflow.rs
Labels: type: feature

#715 feat: add token estimation feature
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/message.rs
  crates/forge_domain/src/orch.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/open_router/response.rs
Labels: type: feature, 🙋 Bounty claim

#722 feat: add provider in `/info`
  crates/forge_main/src/info.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
Labels: type: feature, 🙋 Bounty claim

#737 fix: fs tool usage prompt to include the correct calculation
  crates/forge_services/src/tools/fs/fs_read.rs
Labels: type: fix

#738 fix: remove duplicate tool call params from result
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/tool_call_record.rs
Labels: type: fix

#734 feat: ensure agent doesn't quit in-between task
  Cargo.lock
  crates/forge_display/src/title.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/inquire.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/followup.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/mod.rs
  crates/forge_services/src/tools/registry.rs
  forge.default.yaml
  templates/partial-tool-required.hbs
Labels: type: feature

#739 fix(tools): use JsonSchema instead of XML to Parse Tools
  crates/forge_display/src/diff.rs
  crates/forge_display/src/markdown.rs
  crates/forge_display/src/title.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
  crates/forge_domain/src/tool_call.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_spinner/src/lib.rs
  forge.default.yaml
  templates/partial-tool-information.hbs
  templates/partial-tool-required.hbs
  templates/partial-tool-use-example.hbs
Labels: type: feature, type: fix

#749 fix(tools): update tool names to use consistent naming convention
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/followup.rs
  forge.default.yaml
  templates/partial-tool-information.hbs
  templates/partial-tool-required.hbs
Labels: type: fix

#752 fix(markdown): add dim attribute to code block style for better visibility
  crates/forge_display/src/markdown.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/tool_call_record.rs
Labels: type: fix

#751 fix: zero usage
  crates/forge_domain/src/orch.rs
Labels: type: fix, 🙋 Bounty claim

#758 feat: allow search tool to accept file path to search in
  crates/forge_services/src/tools/fs/fs_find.rs
Labels: type: feature

#764 fix: never reveal tool name to user
  templates/partial-tool-information.hbs
Labels: type: feature, type: fix

#745 fix: add range support for fetch tool
  crates/forge_display/src/diff.rs
  crates/forge_display/src/snapshots/forge_display__diff__tests__diff_printer_simple_diff.snap
  crates/forge_display/src/snapshots/forge_display__diff__tests__file_source.snap
  crates/forge_domain/src/fixtures/tool_call_01.md
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/text_utils.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/clipper.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/metadata.rs
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_deep_directory_creation.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_invalid_rust.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_single_directory_creation.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_success.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_valid_rust.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_different_separators.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_overwrite.snap
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_html_content.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_large_content_temp_file.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_raw_content.snap
Labels: type: feature, 🙋 Bounty claim

#773 fix: update CI workflow to trigger on tag pushes instead of main branch
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: fix

#776 fix: update CI workflow to trigger on tag pushes and update dependenc…
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
Labels: type: fix

#777 fix: add forge_tool_attempt_completion to software-designer agent tools
  forge.default.yaml
Labels: type: fix

#748 fix: add support for range in shell
  Cargo.lock
  crates/forge_display/src/title.rs
  crates/forge_domain/src/shell.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/fs_write.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/mod.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_html_content.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_large_content_minimal.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_large_content_temp_file.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__fetch__tests__fetch_raw_content.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_ansi_preserved.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_ansi_stripped.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_large_command.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_no_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_small_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_working_directory.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__shell_both_streams.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__shell_multiple_commands.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__shell_stderr_with_success.snap
Labels: type: feature, type: fix, 🙋 Bounty claim

#775 fix: compaction spinner updates and interruption
  Cargo.lock
  crates/forge_main/src/ui.rs
  crates/forge_spinner/Cargo.toml
  crates/forge_spinner/src/lib.rs
Labels: type: fix, 🙋 Bounty claim

#783 fix: enhance compaction spinner updates and interrupt handling
  crates/forge_main/src/ui.rs
Labels: type: fix

#788 refactor(domain): standardize tool input types across services
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/tool_input.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/shell.rs
Labels: type: chore

#720 feat: add `update` functionality on startup and an update command for manual updates
  Cargo.lock
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/update.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/banner.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_main/src/update.rs
  forge.default.yaml
Labels: type: feature, 🙋 Bounty claim

#796 chore: track model across all events
  crates/forge_main/src/ui.rs
  crates/forge_tracker/src/dispatch.rs
  crates/forge_tracker/src/event.rs
Labels: type: chore

#799 fix: improve error diagnostics and file operation feedback
  crates/forge_domain/src/orch.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_deep_directory_creation.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_invalid_rust.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_single_directory_creation.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_success.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_valid_rust.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_different_separators.snap
  crates/forge_services/src/tools/fs/snapshots/forge_services__tools__fs__fs_write__test__fs_write_with_overwrite.snap
  forge.default.yaml
Labels: type: fix

#800 fix: include tool description in schema
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
  crates/forge_domain/src/tool_usage.rs
Labels: type: fix

#802 chore: update `antinomy.ai` links in `README`
  README.md
Labels: type: chore

#805 fix: quotation issues in windows
  crates/forge_infra/src/executor.rs
Labels: type: fix

#793 feat: persist `mode` in `forge.yaml`
  crates/forge_main/Cargo.toml
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#806 fix: correct tag in usage instructions for Completion tool
  crates/forge_services/src/tools/completion.rs
Labels: type: fix

#803 feat: support environment variables across directory hierarchy
  crates/forge_infra/src/env.rs
Labels: type: feature

#807 fix: consolidate question handling into forge_tool_attempt_completion
  crates/forge_services/src/tools/completion.rs
  forge.default.yaml
  templates/partial-tool-information.hbs
  templates/partial-tool-required.hbs
Labels: type: fix

#808 chore: store model ID with each conversation message
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/orch.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/open_router/request.rs
  crates/forge_provider/src/open_router/transformers/drop_tool_call.rs
  crates/forge_provider/src/open_router/transformers/set_cache.rs
  crates/forge_services/src/compaction.rs
Labels: type: chore

#812 fix: application version
  .github/workflows/ci.yml
  .github/workflows/forge-automation.yml
  .github/workflows/release-homebrew.yml
  .github/workflows/release-npm.yml
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/jobs/draft_release.rs
  crates/forge_ci/src/lib.rs
  crates/forge_ci/src/workflow.rs
  crates/forge_ci/tests/ci.rs
Labels: type: fix

#814 fix: app version
  .github/workflows/ci.yml
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/jobs/mod.rs
  crates/forge_ci/src/jobs/release_draft.rs
  crates/forge_ci/src/jobs/release_homebrew.rs
  crates/forge_ci/src/jobs/release_npm.rs
Labels: type: fix

#815 fix: correct release ID reference in CI workflow
  .github/workflows/ci.yml
  crates/forge_ci/src/jobs/build.rs
Labels: type: fix

#813 fix: auto update
  crates/forge_main/src/ui.rs
  crates/forge_main/src/update.rs
Labels: type: fix

#810 fix: infinite spinner unstable internet
  crates/forge_provider/src/builder.rs
Labels: type: fix

#818 fix(domain): ensure workflow model updates agent compaction configurations
  crates/forge_display/src/markdown.rs
  crates/forge_domain/src/conversation.rs
Labels: type: fix

#820 fix: improve agent interaction with completion feedback
  crates/forge_domain/src/orch.rs
  forge.default.yaml
Labels: type: fix

#819 chore: rename open router to antinomy
  crates/forge_provider/src/builder.rs
  crates/forge_provider/src/forge_provider/error.rs
  crates/forge_provider/src/forge_provider/mod.rs
  crates/forge_provider/src/forge_provider/model.rs
  crates/forge_provider/src/forge_provider/parameters.rs
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_provider/src/forge_provider/request.rs
  crates/forge_provider/src/forge_provider/response.rs
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__assistant_message_with_tool_call_conversion.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__message_with_special_chars.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__tool_message_conversion.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__tool_message_typescript_code.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__tool_message_with_special_chars.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__request__tests__user_message_conversion.snap
  crates/forge_provider/src/forge_provider/tool_choice.rs
  crates/forge_provider/src/forge_provider/transformers/combine.rs
  crates/forge_provider/src/forge_provider/transformers/drop_tool_call.rs
  crates/forge_provider/src/forge_provider/transformers/identity.rs
  crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
  crates/forge_provider/src/forge_provider/transformers/mod.rs
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  crates/forge_provider/src/forge_provider/transformers/set_cache.rs
  crates/forge_provider/src/forge_provider/transformers/tool_choice.rs
  crates/forge_provider/src/forge_provider/transformers/transformer.rs
  crates/forge_provider/src/forge_provider/transformers/when.rs
  crates/forge_provider/src/lib.rs
Labels: type: chore

#797 feat(mcp): add support for mcp via `.mcp.json`
  Cargo.lock
  Cargo.toml
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/mcp.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_domain/src/tool_name.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_infra/src/mcp_client.rs
  crates/forge_infra/src/mcp_server.rs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/tools_display.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/request.rs
  crates/forge_provider/src/forge_provider/request.rs
  crates/forge_provider/src/forge_provider/tool_choice.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/mcp/manager.rs
  crates/forge_services/src/mcp/mod.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/mcp/tool.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/registry.rs
Labels: type: feature

#828 fix: `.mcp.json` deserialization
  crates/forge_domain/src/mcp.rs
Labels: type: fix, type: chore

#830 chore: drop Optional fields in Mcp Servers
  crates/forge_domain/src/mcp.rs
  crates/forge_infra/src/mcp_client.rs
Labels: type: chore

#829 fix(mcp): change atomic ordering from SeqCst to Relaxed for reconnect logic
  crates/forge_infra/src/mcp_client.rs
  crates/forge_services/src/mcp/service.rs
Labels: type: fix

#831 fix(ui): ensure command registration occurs after workflow initialization
  crates/forge_main/src/ui.rs
Labels: type: fix

#834 fix(ui): add spinners for custom commands
  crates/forge_main/src/ui.rs
  forge.yaml
Labels: type: feature

#836 fix: add cache control only for the models that supports it
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  crates/forge_provider/src/forge_provider/transformers/transformer.rs
Labels: type: fix

#840 fix(provider): improve error handling for stream termination and API responses
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/orch.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/anthropic/request.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/error.rs
  crates/forge_provider/src/forge_provider/error.rs
  crates/forge_provider/src/forge_provider/mod.rs
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_provider/src/forge_provider/response.rs
  crates/forge_provider/src/forge_provider/responses.jsonl
  crates/forge_provider/src/lib.rs
  crates/forge_provider/src/retry.rs
  crates/forge_services/src/provider.rs
Labels: type: fix

#841 fix: force update of @antinomyhq/forge package in execute_update_command
  crates/forge_main/src/update.rs
Labels: type: fix

#825 fix: execute shell commands correctly
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/api.rs
  crates/forge_infra/src/executor.rs
  crates/forge_main/src/ui.rs
  crates/forge_main/src/update.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tools/registry.rs
Labels: type: fix

#835 fix(ui): align tool numbering with consistent padding
  crates/forge_main/src/tools_display.rs
Labels: type: fix

#847 fix: avoid caching models on ui
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#849 fix(domain): resolve serde deserialization errors for conversation loading
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation.rs
Labels: type: fix

#839 chore: added conversation to error context
  Cargo.lock
  crates/forge_main/src/ui.rs
  crates/forge_tracker/Cargo.toml
  crates/forge_tracker/src/dispatch.rs
  crates/forge_tracker/src/event.rs
Labels: type: chore

#852 fix: standardize error output using eprintln instead of println
  crates/forge_display/src/diff.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/registry.rs
Labels: type: fix

#845 fix(tools): return error to agent instead of raising exception
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/tool_service.rs
  forge.default.yaml
  forge.yaml
Labels: type: fix

#853 chore(conversation): add All Subscriptions section to HTML rendering
  crates/forge_domain/src/conversation_html.rs
Labels: type: chore

#846 feat: utilise tool supported setting from api
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/model.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/forge_provider/model.rs
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_services/src/provider.rs
  forge.default.yaml
  forge.yaml
  templates/partial-tool-information.hbs
  templates/partial-tool-required.hbs
Labels: type: feature

#862 fix(ui): add spinner feedback during conversation initialization
  crates/forge_main/src/ui.rs
Labels: type: fix

#865 chore: collect LLM response message
  crates/forge_main/src/ui.rs
Labels: type: chore

#867 fix: error message format for tracing
  crates/forge_domain/src/orch.rs
  crates/forge_services/src/tool_service.rs
Labels: type: fix

#868 feat: add explanation field to forge tools
  crates/forge_domain/src/tool_input.rs
  crates/forge_services/src/clipper.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/followup.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_list.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/shell.rs
Labels: type: feature

#871 chore: update the explanation description
  crates/forge_domain/src/tool_input.rs
Labels: type: chore

#876 fix: remove assignment of `top_p` in Open AI transformer
  crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
Labels: type: fix

#880 fix(retry): enhance error detection with recursive checking and comprehensive tests
  crates/forge_provider/src/error.rs
  crates/forge_provider/src/forge_provider/responses.jsonl
  crates/forge_provider/src/retry.rs
Labels: type: fix

#881 fix(doc): improve documentation for file reading functionality and clarify usage
  crates/forge_services/src/tools/fs/fs_read.rs
Labels: type: fix, type: docs

#882 refactor(tests): streamline sequence finding tests and improve coverage
  crates/forge_services/src/compaction.rs
Labels: type: chore
