Repository antinomyhq/forge, pull requests merged in 2025-04, with the labels that each got.

#604 fix: preserve coloured output for sbt tests
  crates/forge_services/src/tools/shell/executor.rs
Labels: type: fix

#607 fix: improve write message for `fs_write` tool
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/utils/path_validation.rs
Labels: type: feature

#596 feat: implement undo tool
  crates/forge_fs/src/lib.rs
  crates/forge_infra/src/fs_snap.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/mod.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_snaps/Cargo.toml
  crates/forge_snaps/src/service.rs
  crates/forge_snaps/src/snapshot.rs
  forge.default.yaml
Labels: type: feature

#609 refactor: remove Qdrant and OpenAI embedding service references from the codebase
  Cargo.lock
  Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/env.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/embedding.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_infra/src/qdrant.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell/shell_tool.rs
Labels: type: chore

#613 feat: make forge LMStudio compatible
  crates/forge_provider/src/open_router/model.rs
Labels: type: feature

#614 feat: Enhance System Context with Dynamic Variables and Re-rendering
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/system_context.rs
  crates/forge_services/src/template.rs
  forge.default.yaml
  plans/2025-04-02-system-context-rendering-final.md
  plans/2025-04-02-system-context-rendering-v1.md
  plans/2025-04-02-system-context-rendering-v2.md
  templates/partial-act-mode.hbs
  templates/partial-plan-mode.hbs
  templates/system-prompt-engineer.hbs
Labels: type: feature

#600 feat: use request token usage for compaction
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/compaction.rs
  crates/forge_domain/src/orch.rs
Labels: type: feature

#617 fix: implement System Prompts for plan mode
  forge.default.yaml
  templates/partial-plan-mode.hbs
  templates/system-prompt-engineer-act.hbs
  templates/system-prompt-engineer-plan.hbs
  templates/system-prompt-engineer.hbs
Labels: type: fix

#622 feat: add comprehensive documentation for new features including coding agent, built-in commands, security, image upload, autocomplete, multi-agent architecture, WYSIWYG shell experience, and command interruption
  README.md
  docs/features/ai-shell.md
  docs/features/application-logs.md
  docs/features/autocomplete.md
  docs/features/coding-agent.md
  docs/features/command-interruption.md
  docs/features/commands.md
  docs/features/custom-workflows.md
  docs/features/image-upload.md
  docs/features/index.md
  docs/features/multi-agent.md
  docs/features/operation-modes.md
  docs/features/provider-configuration.md
  docs/features/security.md
  docs/features/wysiwyg.md
  docs/index.md
Labels: type: feature, type: docs

#623 fix: update system prompt to conditionally display custom rules section
  templates/system-prompt-engineer-plan.hbs
Labels: type: fix

#626 refactor: simplify command output formatting in shell execution
  crates/forge_services/src/tools/shell/shell_tool.rs
Labels: type: chore

#625 fix: client connection settings
  crates/forge_provider/src/builder.rs
  crates/forge_provider/src/open_router/provider.rs
Labels: type: fix

#627 fix: file-search tool should be used to search for files
  crates/forge_display/src/grep.rs
  crates/forge_display/src/snapshots/forge_display__grep__tests__combined_grep_suite.snap
  crates/forge_display/src/title.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/utils/mod.rs
  crates/forge_services/src/tools/utils/path.rs
  forge.yaml
Labels: type: fix

#608 feat: log request url with errors for more clearity
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/lib.rs
  crates/forge_provider/src/open_router/provider.rs
  crates/forge_provider/src/utils.rs
Labels: type: feature

#631 fix: remove timeout
  crates/forge_provider/src/builder.rs
Labels: type: fix

#620 fix: retry on upstream errors
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/suggestion.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/builder.rs
  crates/forge_provider/src/lib.rs
  crates/forge_provider/src/open_router/provider.rs
  crates/forge_provider/src/retry.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell/shell_tool.rs
  forge.default.yaml
  plans/2025-04-06-retry-config-migration.md
Labels: type: fix

#638 feat: initialize a conversation from a dump file
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/compaction.rs
  crates/forge_fs/src/lib.rs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/template.rs
  templates/system-prompt-context-summarizer.hbs
Labels: type: feature

#640 fix: improve auto-compaction logic
  crates/forge_domain/src/compaction.rs
  forge.default.yaml
  templates/system-prompt-context-summarizer.hbs
Labels: type: fix

#651 feat: implement auto update functionality
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/main.rs
Labels: type: feature

#655 feat: setting up default models
  README.md
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/src/completer/input_completer.rs
  templates/system-prompt-engineer-plan.hbs
Labels: type: feature

#657 feat: ability to customize default agent
  Cargo.lock
  README.md
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/forge_default.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/loader.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/merge.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/temperature.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_inte/tests/test_workflow.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/request.rs
  crates/forge_provider/src/open_router/model.rs
  crates/forge_provider/src/open_router/request.rs
  crates/forge_services/src/tools/show_user.rs
  forge.yaml
Labels: type: feature, type: chore

#661 fix: broken STDIO
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#662 fix: broken CLI formatting
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/tool.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tool_definition.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_list.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/outline/tests/css.rs
  crates/forge_services/src/tools/outline/tests/java.rs
  crates/forge_services/src/tools/outline/tests/javascript.rs
  crates/forge_services/src/tools/outline/tests/misc.rs
  crates/forge_services/src/tools/outline/tests/mod.rs
  crates/forge_services/src/tools/outline/tests/python.rs
  crates/forge_services/src/tools/outline/tests/rust.rs
  crates/forge_services/src/tools/outline/tests/scala.rs
  crates/forge_services/src/tools/outline/tests/tsx.rs
  crates/forge_services/src/tools/outline/tests/typescript.rs
  crates/forge_services/src/tools/patch/apply.rs
  crates/forge_services/src/tools/patch/apply_json.rs
  crates/forge_services/src/tools/patch/parse.rs
  crates/forge_services/src/tools/shell/shell_tool.rs
  crates/forge_services/src/tools/show_user.rs
  forge.yaml
  plans/2025-04-11-tool-call-context-implementation.md
Labels: type: fix, type: chore

#668 fix: add default value for agents in Workflow struct
  crates/forge_domain/src/workflow.rs
Labels: type: fix

#670 feat: shell style prompt improvements
  crates/forge_main/src/prompt.rs
  forge.yaml
  templates/system-prompt-engineer-plan.hbs
Labels: type: feature

#667 feat(cli): add `/model` command for interactive model selection
  Cargo.lock
  Cargo.toml
  crates/forge_api/Cargo.toml
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/loader.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_infra/src/env.rs
  crates/forge_inte/Cargo.toml
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/conversation.rs
  docs/features/commands.md
  forge.yaml
  plans/2025-04-16-model-selection-command.md
Labels: type: feature

#671 fix(ui): handle errors in model selection prompt
  crates/forge_main/src/ui.rs
Labels: type: fix

#673 fix: remove redundant title agent functionality and related code
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  forge.default.yaml
  forge.yaml
  templates/system-prompt-title-generator.hbs
Labels: type: fix, type: chore

#675 perf(models): implement model caching to improve selection performance
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#676 docs: update README for improved getting started instructions and provider configuration
  README.md
Labels: type: docs

#672 feat(shell): use `!` to run arbitary shell commands without exiting.
  Cargo.lock
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/shell.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tools/queries/css.rkt
  crates/forge_services/src/tools/queries/java.rkt
  crates/forge_services/src/tools/queries/javascript.rkt
  crates/forge_services/src/tools/queries/python.rkt
  crates/forge_services/src/tools/queries/rust.rkt
  crates/forge_services/src/tools/queries/scala.rkt
  crates/forge_services/src/tools/queries/typescript.rkt
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_services/src/tools/shell/executor.rs
  crates/forge_services/src/tools/shell/mod.rs
  docs/features/commands.md
Labels: type: feature, type: chore

#674 feat(compact): add `/compact` command to reduce context size
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/compaction_result.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/compaction.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  forge.default.yaml
Labels: type: feature

#678 fix(compaction): improve context summarization with authoritative framing
  crates/forge_services/src/compaction.rs
Labels: type: feature

#679 fix(compaction): move decision logic to orchestrator for better separation of concerns
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_services/src/compaction.rs
  crates/forge_services/src/conversation.rs
Labels: type: feature

#680 feat: improve the `/help` and `/info` commands
  crates/forge_main/src/banner
  crates/forge_main/src/banner.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/patch/apply.rs
  crates/forge_services/src/tools/patch/marker.rs
  crates/forge_services/src/tools/patch/mod.rs
  crates/forge_services/src/tools/patch/parse.rs
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-4.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-5.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-6.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_block-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_block.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_search_new_file-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_search_new_file.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__error_messages-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__error_messages.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced-4.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace-4.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__invalid_rust_replace-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__invalid_rust_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__multiple_blocks-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__multiple_blocks.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__valid_rust_replace-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__valid_rust_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__whitespace_preservation-2.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__whitespace_preservation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__patch__test__comprehensive_error_tests.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__patch__test__comprehensive_patch_tests.snap
  forge.default.yaml
  templates/system-prompt-engineer-plan.hbs
  templates/system-prompt-git-commit.hbs
  templates/system-prompt-github-engineer.hbs
  templates/system-prompt-github-issue-planner.hbs
  templates/system-prompt-github-plan-reviser.hbs
  templates/system-prompt-github-pr-updater.hbs
  templates/system-prompt-github-pull-request.hbs
  templates/system-prompt-github-review-handler.hbs
  templates/system-prompt-help.hbs
Labels: type: feature, type: fix, type: chore

#677 feat: enhance chat response handling with progress indication
  Cargo.lock
  Cargo.toml
  crates/forge_display/Cargo.toml
  crates/forge_display/src/diff.rs
  crates/forge_display/src/lib.rs
  crates/forge_display/src/markdown.rs
  crates/forge_display/src/snapshots/forge_display__diff__tests__diff_printer_simple_diff.snap
  crates/forge_display/src/snapshots/forge_display__diff__tests__file_source.snap
  crates/forge_display/src/title.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/text_utils.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/banner
  crates/forge_main/src/banner.rs
  crates/forge_main/src/console.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/normalize.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/mod.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_services/src/tools/show_user.rs
  crates/forge_spinner/Cargo.toml
  crates/forge_spinner/src/lib.rs
  forge.default.yaml
  templates/partial-show-user.hbs
  templates/system-prompt-engineer-act.hbs
Labels: type: feature

#682 feat(cli): enhance command output and refactor formatting
  Cargo.lock
  crates/forge_main/Cargo.toml
  crates/forge_main/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/tools_display.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#684 feat(display): add plain text diff output to patch tool
  Cargo.lock
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/tool_call_parser.rs
  crates/forge_infra/src/executor.rs
  crates/forge_provider/src/open_router/provider.rs
  crates/forge_provider/src/open_router/request.rs
  crates/forge_provider/src/open_router/transformers/set_cache.rs
  crates/forge_provider/src/open_router/transformers/transformer.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/patch.rs
  forge.yaml
  templates/partial-system-info.hbs
  templates/partial-tool-information.hbs
Labels: type: feature, type: fix

#690 fix(loader): ensure explicit workflow files are merged with default
  crates/forge_api/src/loader.rs
  crates/forge_display/src/snapshots/forge_display__diff__tests__diff_printer_simple_diff.snap
  crates/forge_display/src/snapshots/forge_display__diff__tests__file_source.snap
Labels: type: feature, type: fix, type: chore

#692 fix: refactor string formatting to use new syntax
  crates/forge_ci/tests/ci.rs
  crates/forge_ci/tests/forge_automation.rs
  crates/forge_display/src/diff.rs
  crates/forge_display/src/grep.rs
  crates/forge_display/src/title.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/provider.rs
  crates/forge_domain/src/temperature.rs
  crates/forge_domain/src/text_utils.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_infra/src/env.rs
  crates/forge_main/build.rs
  crates/forge_main/src/auto_update.rs
  crates/forge_main/src/banner.rs
  crates/forge_main/src/completer/search_term.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/tools_display.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/anthropic/request.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/builder.rs
  crates/forge_provider/src/open_router/provider.rs
  crates/forge_provider/src/open_router/response.rs
  crates/forge_provider/src/open_router/transformers/transformer.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/compaction.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_snaps/src/service.rs
  crates/forge_snaps/src/snapshot.rs
  crates/forge_spinner/src/lib.rs
  crates/forge_template/src/element.rs
  crates/forge_tool_macros/src/lib.rs
  crates/forge_tracker/src/dispatch.rs
  crates/forge_walker/src/walker.rs
Labels: type: feature, type: fix, type: chore

#693 fix(template): template rendering error
  crates/forge_services/src/template.rs
Labels: type: fix

#688 feat(title): add timestamp handling to TitleFormat and update dependencies
  Cargo.lock
  crates/forge_display/Cargo.toml
  crates/forge_display/src/snapshots/forge_display__diff__tests__diff_printer_simple_diff.snap
  crates/forge_display/src/snapshots/forge_display__diff__tests__file_source.snap
  crates/forge_display/src/title.rs
Labels: type: feature

#695 feat: implement dedicated planner mode with multi-agent architecture
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_failed_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_successful_call.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_call_record__tests__display_with_special_chars.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__display_full.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__display_minimal.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__display_special_chars.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__snapshot_full.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__snapshot_minimal.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__snapshot_with_special_chars.snap
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
  crates/forge_domain/src/text_utils.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_domain/src/tool_call_parser.rs
  crates/forge_domain/src/tool_call_record.rs
  crates/forge_domain/src/tool_definition.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_inte/tests/test_workflow.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/open_router/response.rs
  crates/forge_provider/src/open_router/snapshots/forge_provider__open_router__request__tests__tool_message_conversion.snap
  crates/forge_provider/src/open_router/snapshots/forge_provider__open_router__request__tests__tool_message_typescript_code.snap
  crates/forge_provider/src/open_router/snapshots/forge_provider__open_router__request__tests__tool_message_with_special_chars.snap
  crates/forge_services/src/compaction.rs
  crates/forge_services/src/snapshots/forge_services__tool_service__test__failed_tool_call.snap
  crates/forge_services/src/snapshots/forge_services__tool_service__test__successful_tool_call.snap
  crates/forge_services/src/snapshots/forge_services__tool_service__test__tool_not_found.snap
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_list.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/shell.rs
  docs/features/custom-workflows.md
  forge.default.yaml
  templates/partial-system-info.hbs
  templates/partial-tool-information.hbs
  templates/system-prompt-advocate.hbs
  templates/system-prompt-engineer-act.hbs
  templates/system-prompt-engineer-plan.hbs
Labels: type: feature

#698 fix(orchestrator): improve handling of interrupted tool responses
  crates/forge_display/src/markdown.rs
  crates/forge_domain/src/orch.rs
Labels: type: fix

#699 fix(template): improve implementation plan md format for clarity and consistency
  templates/system-prompt-engineer-plan.hbs
Labels: type: chore

#700 fix(software-designer): restrict agent to plan creation only
  forge.default.yaml
Labels: type: fix

#702 fix(agent): disable tool support for software engineer and designer agents
  forge.default.yaml
Labels: type: fix

#706 feat(fs): support reading file ranges
  Cargo.lock
  crates/forge_api/src/loader.rs
  crates/forge_fs/Cargo.toml
  crates/forge_fs/src/error.rs
  crates/forge_fs/src/file_info.rs
  crates/forge_fs/src/file_size.rs
  crates/forge_fs/src/is_binary.rs
  crates/forge_fs/src/lib.rs
  crates/forge_fs/src/meta.rs
  crates/forge_fs/src/read.rs
  crates/forge_fs/src/read_range.rs
  crates/forge_fs/src/write.rs
  crates/forge_infra/src/fs_read.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/registry.rs
  plans/2025-04-26-large-file-read-range-support-v3.md
  plans/2025-04-27-large-file-read-range-support-v4.md
Labels: type: feature

#709 feat(model): model selection is mandatory and persisted after startup
  Cargo.lock
  crates/forge_api/src/executor.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/loader.rs
  crates/forge_display/src/title.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/suggestion.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/workflow.rs
  crates/forge_spinner/src/lib.rs
  forge.yaml
Labels: type: chore

#714 fix(ui): enhance model selection help message for better user guidance
  crates/forge_main/src/ui.rs
Labels: type: fix

#718 fix(markdown): update color settings for inline code style in MarkdownFormat
  crates/forge_display/src/markdown.rs
Labels: type: fix
