Repository antinomyhq/forge, pull requests merged in 2025-03, with the labels that each got.

#410 Rename DispatchEvent to Event
  crates/forge_app/src/conversation.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
Labels: type: fix

#417 feat: add overwrite option to FSWriteInput for file writing behavior
  crates/forge_app/src/tools/fs/fs_write.rs
Labels: type: feature

#427 feat(template): add agent reference to template service
  .gitignore
  crates/forge_api/src/executor.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/provider.rs
  crates/forge_app/src/suggestion.rs
  crates/forge_app/src/template.rs
  crates/forge_app/src/tool_service.rs
  crates/forge_app/src/tools/knowledge.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  forge.yaml
Labels: type: feature

#429 feat(fs-patch): replace fuzzy patching with operation-based exact patching
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/patch/apply_json.rs
  crates/forge_app/src/tools/patch/mod.rs
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__append_empty_search.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__comprehensive_error_tests.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__comprehensive_patch_tests.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__delete_empty_replace.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__delete_single_line_only.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__different_replacements_in_sequence.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__emoji_replacement.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__empty_search_text.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__exact_match_single_word.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__exact_threshold_match.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__fuzzy_match_hyphenated_pattern.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__fuzzy_match_with_extra_characters.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__fuzzy_match_with_prefix.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__mixed_unicode_ascii.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__multiple_line_endings.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__nested_replacements.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__overlapping_matches.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__prefers_exact_matches_over_fuzzy.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__preserve_indentation.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__replaces_only_first_match.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__sequential_non_overlapping_replacements.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__sequential_replacements_on_identical_text.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__tab_characters.snap
  crates/forge_app/src/tools/patch/snapshots/forge_app__tools__patch__apply_json__test__unicode_characters.snap
Labels: type: feature

#434 feat: display Version in `/info`
  crates/forge_main/src/info.rs
  crates/forge_tracker/src/lib.rs
Labels: type: feature

#431 fix: Make walker depth optional and more flexible in template agent
  .ignore
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
Labels: type: fix, type: chore

#441 chore: ability to disable `test_find_cat_name`
  .config/nextest.toml
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
  crates/forge_inte/tests/api_spec.rs
Labels: type: chore

#378 feat: ability to attach images
  Cargo.lock
  crates/forge_api/src/loader.rs
  crates/forge_app/Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/attachment.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/file_read.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_open_router/src/anthropic/request.rs
  crates/forge_open_router/src/open_router/request.rs
  crates/forge_open_router/src/open_router/snapshots/forge_open_router__open_router__request__tests__image_url_with_detail.snap
  crates/forge_open_router/src/open_router/snapshots/forge_open_router__open_router__request__tests__message_mixed_content.snap
  crates/forge_open_router/src/open_router/snapshots/forge_open_router__open_router__request__tests__message_with_multiple_images.snap
  crates/forge_open_router/src/open_router/snapshots/forge_open_router__open_router__request__tests__message_with_single_image.snap
  crates/forge_walker/src/walker.rs
Labels: type: feature

#443 fix: add diff output display to `apply_json.rs`
  crates/forge_app/src/tools/patch/apply_json.rs
Labels: type: fix

#445 feat(patch): support multiple-patch operations in a single call
  crates/forge_app/src/tools/fs/fs_write.rs
  crates/forge_app/src/tools/patch/apply.rs
  crates/forge_app/src/tools/patch/apply_json.rs
  crates/forge_display/src/diff.rs
Labels: type: feature, type: fix

#446 refactor: migrate from content-based to event-based communication model
  crates/forge_api/src/executor.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/chat_request.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/orch.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/ui.rs
Labels: type: chore

#453 fix: system prompt improvements and shell tool formatting
  .gitignore
  crates/forge_app/src/template.rs
  crates/forge_app/src/tools/shell/shell_tool.rs
  crates/forge_main/src/ui.rs
  templates/system-prompt-engineer.hbs
  templates/system-prompt-title-generator.hbs
Labels: type: fix

#460 feat: Add Act and Plan modes
  .config/nextest.toml
  README.md
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/src/conversation.rs
  crates/forge_app/src/template.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/message.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/src/banner
  crates/forge_main/src/banner.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/lib.rs
  crates/forge_main/src/mod.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  forge.yaml
  templates/system-prompt-engineer.hbs
Labels: type: feature, type: chore

#442 feat(oauth): implement authentication flow with login and logout
  Cargo.lock
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/attachment.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/provider.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/shell/shell_tool.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/provider.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/auth.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_oauth/Cargo.toml
  crates/forge_oauth/src/callback.rs
  crates/forge_oauth/src/error.rs
  crates/forge_oauth/src/html_templates/error_page.html
  crates/forge_oauth/src/html_templates/missing_params_page.html
  crates/forge_oauth/src/html_templates/not_found_page.html
  crates/forge_oauth/src/html_templates/success_page.html
  crates/forge_oauth/src/lib.rs
  crates/forge_oauth/src/oauth.rs
  crates/forge_oauth/src/user_info.rs
  crates/forge_open_router/src/builder.rs
  crates/forge_open_router/src/lib.rs
  crates/forge_open_router/src/open_router/api.rs
  crates/forge_open_router/src/open_router/mod.rs
  crates/forge_open_router/src/open_router/provider.rs
  crates/forge_open_router/src/open_router/transformers/pipeline.rs
Labels: type: feature

#464 Revert "feat(oauth): implement authentication flow with login and logout"
  Cargo.lock
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/attachment.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/provider.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/shell/shell_tool.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/provider.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/auth.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_oauth/Cargo.toml
  crates/forge_oauth/src/callback.rs
  crates/forge_oauth/src/error.rs
  crates/forge_oauth/src/html_templates/error_page.html
  crates/forge_oauth/src/html_templates/missing_params_page.html
  crates/forge_oauth/src/html_templates/not_found_page.html
  crates/forge_oauth/src/html_templates/success_page.html
  crates/forge_oauth/src/lib.rs
  crates/forge_oauth/src/oauth.rs
  crates/forge_oauth/src/user_info.rs
  crates/forge_open_router/src/builder.rs
  crates/forge_open_router/src/lib.rs
  crates/forge_open_router/src/open_router/api.rs
  crates/forge_open_router/src/open_router/mod.rs
  crates/forge_open_router/src/open_router/provider.rs
  crates/forge_open_router/src/open_router/transformers/pipeline.rs
Labels: type: feature

#469 fix: change logging format to `json`
  crates/forge_tracker/src/log.rs
Labels: type: fix

#470 doc: add application logs documentation to README
  README.md
Labels: type: docs

#471 chore: move dependencies to root `Cargo.toml`
  Cargo.lock
  Cargo.toml
  crates/forge_api/Cargo.toml
  crates/forge_app/Cargo.toml
  crates/forge_ci/Cargo.toml
  crates/forge_display/Cargo.toml
  crates/forge_domain/Cargo.toml
  crates/forge_infra/Cargo.toml
  crates/forge_inte/Cargo.toml
  crates/forge_main/Cargo.toml
  crates/forge_open_router/Cargo.toml
  crates/forge_stream/Cargo.toml
  crates/forge_tool_macros/Cargo.toml
  crates/forge_tracker/Cargo.toml
  crates/forge_walker/Cargo.toml
Labels: type: chore

#474 feat(provider): add support for custom provider URLs
  README.md
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/provider.rs
  crates/forge_infra/src/env.rs
Labels: type: feature

#476 feat(tools): introduce agent-level tool support configuration
  README.md
  crates/forge_app/src/provider.rs
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_inte/tests/test_workflow.yaml
  crates/forge_open_router/src/anthropic/provider.rs
  crates/forge_open_router/src/builder.rs
  crates/forge_open_router/src/open_router/api.rs
  forge.default.yaml
  forge.yaml
Labels: type: feature

#475 feat: add help command mode with dedicated help agent
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  forge.default.yaml
  forge.yaml
  templates/system-prompt-help.hbs
Labels: type: feature

#457 feat: implement file snapshot system
  Cargo.lock
  Cargo.toml
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/loader.rs
  crates/forge_app/Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/attachment.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/tools/fs/fs_remove.rs
  crates/forge_app/src/tools/fs/fs_write.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/patch/apply.rs
  crates/forge_app/src/tools/patch/apply_json.rs
  crates/forge_domain/src/env.rs
  crates/forge_fs/Cargo.toml
  crates/forge_fs/src/lib.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/fs_create_dirs.rs
  crates/forge_infra/src/fs_meta.rs
  crates/forge_infra/src/fs_read.rs
  crates/forge_infra/src/fs_remove.rs
  crates/forge_infra/src/fs_snap.rs
  crates/forge_infra/src/fs_write.rs
  crates/forge_infra/src/infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/ui.rs
  crates/forge_snaps/Cargo.toml
  crates/forge_snaps/src/lib.rs
  crates/forge_snaps/src/service.rs
  crates/forge_tool_macros/src/lib.rs
Labels: type: feature

#481 fix: set `forge_fs` and `forge_walker` to workspace
  Cargo.lock
  Cargo.toml
  crates/forge_snaps/Cargo.toml
  crates/forge_snaps/src/service.rs
Labels: type: fix

#479 fix(ui): integrate tracker dispatch for prompt events in user input handling
  crates/forge_main/src/input.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#478 feat(config): support workflow merge
  Cargo.lock
  Cargo.toml
  README.md
  crates/forge_api/Cargo.toml
  crates/forge_api/src/loader.rs
  crates/forge_app/src/provider.rs
  crates/forge_app/src/tools/fetch.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/merge.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_open_router/src/anthropic/provider.rs
  crates/forge_open_router/src/builder.rs
  crates/forge_open_router/src/open_router/api.rs
  forge.yaml
Labels: enhancement, type: chore, rust

#487 feat: add support for project level rules.
  README.md
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/merge.rs
  templates/system-prompt-engineer.hbs
Labels: type: feature

#496 fix(provider): improve Open AI compatibility and error handling
  Cargo.lock
  crates/forge_api/src/forge_default.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/loader.rs
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/merge.rs
  crates/forge_domain/src/model.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/system_context.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_inte/Cargo.toml
  crates/forge_inte/tests/test_workflow.rs
  crates/forge_inte/tests/test_workflow.yaml
  crates/forge_main/src/info.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_open_router/src/anthropic/response.rs
  crates/forge_open_router/src/open_router/api.rs
  crates/forge_open_router/src/open_router/model.rs
  crates/forge_open_router/src/open_router/provider.rs
  crates/forge_tracker/src/event.rs
  forge.default.yaml
Labels: type: feature, type: fix

#502 fix(open_router): replace OpenAITransformer with DropOpenRouterFields and remove redundant logging
  crates/forge_open_router/src/open_router/transformers/drop_or_fields.rs
  crates/forge_open_router/src/open_router/transformers/mod.rs
  crates/forge_open_router/src/open_router/transformers/pipeline.rs
  crates/forge_tracker/src/dispatch.rs
Labels: type: fix

#494 feat: use queue based system for agents
  crates/forge_api/src/executor.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/attachment.rs
  crates/forge_app/src/conversation.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/provider.rs
  crates/forge_app/src/template.rs
  crates/forge_app/src/tool_service.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_infra/src/fs_read.rs
  crates/forge_infra/src/fs_snap.rs
  crates/forge_infra/src/infra.rs
  crates/forge_inte/tests/api_spec.rs
Labels: type: feature

#499 feat(CLI): add `--event` parameter to dispatch custom events
  Cargo.lock
  crates/forge_api/src/forge_default.rs
  crates/forge_api/src/lib.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/ui.rs
  templates/system-prompt-github-engineer.hbs
Labels: type: feature, type: fix

#504 chore(ci): add Forge Automation workflow
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
Labels: type: chore

#505 fix(ci): update Forge CLI commands to use `--event` parameter for issue processing
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
Labels: type: fix

#509 chore(ci): add comments to issues and PRs with action links in Forge
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
Labels: type: feature, type: chore

#508 fix: add Markdown file requirements for PLAN mode
  templates/system-prompt-engineer.hbs
Labels: type: fix

#511 chore(ci): update GitHub Actions to use generated token for issue and PR comments
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
Labels: type: chore

#514 chore(ci): exclude bot from triggering PR updates in Forge automation
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
Labels: type: chore

#503 feat: allow support for registering custom commands
  Cargo.lock
  README.md
  crates/forge_api/src/loader.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/merge.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/banner.rs
  crates/forge_main/src/completer/command.rs
  crates/forge_main/src/completer/input_completer.rs
  crates/forge_main/src/editor.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_open_router/src/open_router/api.rs
  crates/forge_open_router/src/open_router/response.rs
Labels: type: feature

#519 fix: improve help prompts
  README.md
  templates/system-prompt-help.hbs
Labels: type: fix, type: docs

#520 fix: simplify title generation event logic
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#524 fix: snapshot creation for new files
  crates/forge_api/src/forge_default.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_infra/src/fs_write.rs
  crates/forge_open_router/src/anthropic/provider.rs
  crates/forge_open_router/src/open_router/api.rs
  crates/forge_open_router/src/open_router/response.rs
  forge.default.yaml
  templates/system-prompt-git-commit.hbs
  templates/system-prompt-github-pr.hbs
Labels: type: feature, type: fix

#525 feat: add current date to system context and templates
  crates/forge_app/src/template.rs
  crates/forge_domain/src/system_context.rs
  templates/system-prompt-advocate.hbs
  templates/system-prompt-engineer.hbs
  templates/system-prompt-github-engineer.hbs
  templates/system-prompt-help.hbs
Labels: type: feature

#527 feat(provider): add support for `anthropic_url`
  README.md
  crates/forge_domain/src/provider.rs
  crates/forge_infra/src/env.rs
  crates/forge_open_router/src/builder.rs
  forge.default.yaml
  templates/system-prompt-github-pull-request.hbs
Labels: type: feature, type: chore

#530 fix(templates): enhance PR template with GitHub CLI integration and system info partials
  crates/forge_inte/tests/test_workflow.rs
  forge.default.yaml
  templates/partial-system-info.hbs
  templates/system-prompt-advocate.hbs
  templates/system-prompt-engineer.hbs
  templates/system-prompt-git-commit.hbs
  templates/system-prompt-github-engineer.hbs
  templates/system-prompt-github-pull-request.hbs
  templates/system-prompt-help.hbs
Labels: type: fix

#529 feat: add npm package publishing to CI workflow
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: feature

#533 fix: improve git commit prompt to handle staged changes better
  crates/forge_open_router/src/anthropic/provider.rs
  crates/forge_open_router/src/open_router/mod.rs
  crates/forge_open_router/src/open_router/provider.rs
  templates/system-prompt-git-commit.hbs
Labels: type: fix, type: chore

#542 fix: update GitHub agent configurations
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/ci.rs
  crates/forge_ci/tests/forge_automation.rs
  docs/enhanced-workflow.md
  forge.default.yaml
  templates/system-prompt-github-engineer.hbs
  templates/system-prompt-github-issue-planner.hbs
  templates/system-prompt-github-plan-reviser.hbs
  templates/system-prompt-github-pr-updater.hbs
  templates/system-prompt-github-review-handler.hbs
Labels: type: fix

#546 chore(ci): JSON parsing error with special characters in comments
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/forge_automation.rs
Labels: type: chore

#548 chore(ci): simplify forge event JSON by removing comment body from re…
  .github/workflows/forge-automation.yml
  crates/forge_ci/tests/forge_automation.rs
Labels: type: chore

#551 feat: Add agent disable functionality and enhance command handling
  README.md
  crates/forge_app/src/template.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/system_context.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_main/src/model.rs
  docs/guidelines.md
  forge.default.yaml
  forge.yaml
  templates/system-prompt-engineer.hbs
  templates/system-prompt-github-engineer.hbs
  templates/system-prompt-github-issue-planner.hbs
  templates/system-prompt-github-plan-reviser.hbs
  templates/system-prompt-github-pr-updater.hbs
  templates/system-prompt-github-review-handler.hbs
Labels: type: feature

#554 fix: merge strategy for agent subscriptions
  crates/forge_domain/src/agent.rs
Labels: type: feature, type: fix

#556 feat: add `show_user` tool, refactor FSRead, and improve Agent event handling
  Cargo.lock
  Cargo.toml
  crates/forge_app/Cargo.toml
  crates/forge_app/src/tool_service.rs
  crates/forge_app/src/tools/fs/fs_read.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/registry.rs
  crates/forge_app/src/tools/show_user.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/orch.rs
  crates/forge_main/src/ui.rs
  docs/tool-guidelines.md
  forge.default.yaml
  forge.yaml
  templates/system-prompt-engineer.hbs
Labels: type: feature, type: chore

#557 feat: add Terminal Markdown Display
  .github/workflows/ci.yml
  Cargo.lock
  crates/forge_app/src/tools/fetch.rs
  crates/forge_app/src/tools/fs/fs_find.rs
  crates/forge_app/src/tools/fs/fs_read.rs
  crates/forge_app/src/tools/mod.rs
  crates/forge_app/src/tools/patch/apply_json.rs
  crates/forge_app/src/tools/registry.rs
  crates/forge_app/src/tools/shell/shell_tool.rs
  crates/forge_app/src/tools/think.rs
  crates/forge_ci/tests/ci.rs
  crates/forge_inte/Cargo.toml
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/ui.rs
  forge.default.yaml
  forge.yaml
  templates/partial-show-user.hbs
  templates/system-prompt-engineer.hbs
  templates/system-prompt-help.hbs
Labels: type: feature, type: fix, type: docs

#562 fix: Update message sending logic to include Custom type responses
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/orch.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#565 fix(#561): Redesign conversation state management to address agent persistence after interruptions
  crates/forge_api/src/api.rs
  crates/forge_api/src/executor.rs
  crates/forge_app/src/conversation.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
Labels: type: fix

#568 fix: avoid unwrapping when receiver is dropped.
  Cargo.lock
  crates/forge_api/Cargo.toml
  crates/forge_api/src/executor.rs
Labels: type: fix

#581 fix: update output format for patched files to include status indication
  crates/forge_services/src/tools/patch/apply.rs
  crates/forge_services/src/tools/patch/apply_json.rs
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-5.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_block.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_search_new_file.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__multiple_blocks.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__valid_rust_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__whitespace_preservation.snap
Labels: type: fix

#583 fix: propagate `prompt` errors
  crates/forge_main/src/input.rs
Labels: type: fix

#586 fix: parsing error on models response
  crates/forge_provider/src/builder.rs
  crates/forge_provider/src/open_router/provider.rs
Labels: type: fix

#588 fix: patched files result to return content
  crates/forge_services/src/tools/patch/apply.rs
  crates/forge_services/src/tools/patch/apply_json.rs
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation-5.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__complex_newline_preservation.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_block.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__empty_search_new_file.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_advanced.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace-3.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__fuzzy_search_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__multiple_blocks.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__valid_rust_replace.snap
  crates/forge_services/src/tools/patch/snapshots/forge_services__tools__patch__apply__test__whitespace_preservation.snap
Labels: type: fix

#591 feat: configure temperature agent wise
  README.md
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/orch.rs
  crates/forge_provider/src/open_router/request.rs
  crates/forge_provider/src/open_router/transformers/drop_tool_call.rs
  crates/forge_provider/src/open_router/transformers/set_cache.rs
Labels: type: feature

#593 fix: attachment utf-8 parsing
  crates/forge_domain/src/context.rs
Labels: type: fix

#592 refactor: change Event value type to serde value
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/orch.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/template.rs
Labels: type: chore

#594 fix: update X-Title header and add HTTP-Referer
  crates/forge_provider/src/open_router/provider.rs
Labels: type: fix

#582 feat: Implement automatic context compaction for improved conversation management
  crates/forge_api/src/executor.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/suggestion.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/attachment.rs
  crates/forge_domain/src/compaction.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/services.rs
  crates/forge_domain/src/summarize.rs
  crates/forge_domain/src/text_utils.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/open_router/request.rs
  crates/forge_provider/src/open_router/transformers/drop_tool_call.rs
  crates/forge_provider/src/open_router/transformers/set_cache.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/template.rs
  forge.yaml
  plans/agent-context-compaction-2025-03-24-concise.md
  plans/agent-context-compaction-2025-03-24.md
  plans/agent-context-compaction-2025-03-25-concise.md
  plans/agent-context-compaction-2025-03-25.md
  templates/system-prompt-context-summarizer.hbs
  templates/system-prompt-engineer.hbs
Labels: type: feature

#597 fix: cargo test failing
  crates/forge_domain/src/text_utils.rs
Labels: type: fix

#570 fix: Implement retry mechanism with exponential backoff for agent
  Cargo.lock
  Cargo.toml
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/src/ui.rs
  forge.default.yaml
Labels: type: fix

#601 fix: ensure URLs end with a trailing slash in Provider methods
  crates/forge_domain/src/provider.rs
Labels: type: fix
