Repository antinomyhq/forge, pull requests merged in 2025-07, with the labels that each got.

#1013 fix: replace panic with proper error handling in API key resolution
  crates/forge_infra/src/env.rs
  crates/forge_main/src/main.rs
Labels: type: fix

#1022 chore: add tracker for panic hook
  crates/forge_main/src/main.rs
Labels: type: fix

#1018 chore: add `Requesty` as a Provider
  README.md
  crates/forge_domain/src/provider.rs
  crates/forge_infra/src/env.rs
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  forge.yaml
Labels: type: feature, type: chore

#1016 fix: report more readable errors back to LLM
  Cargo.lock
  Cargo.toml
  crates/forge_app/Cargo.toml
  crates/forge_app/src/error.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_deser_failure.snap
  crates/forge_domain/src/task.rs
  crates/forge_domain/src/tool_name.rs
  crates/forge_domain/src/tools.rs
  crates/forge_provider/src/anthropic/snapshots/forge_provider__anthropic__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/anthropic/snapshots/forge_provider__anthropic__provider__tests__fetch_models_server_error.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__provider__tests__fetch_models_server_error.snap
Labels: type: fix

#1015 chore: use standard ignore filters in walker
  crates/forge_walker/src/walker.rs
Labels: type: chore

#1009 fix: read larger chunks whenever possible
  templates/forge-partial-tool-information.hbs
  templates/forge-partial-tool-instructions.hbs
Labels: type: fix

#1011 feat: add replace-all variant to patch tool
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tools.rs
  crates/forge_services/src/tool_services/fs_patch.rs
Labels: type: feature, type: fix

#1017 fix: add citation rule for code references in prompts
  templates/forge-system-prompt-engineer-act.hbs
  templates/forge-system-prompt-engineer-plan.hbs
Labels: type: fix

#1023 fix: ask agent to self reflect on errors
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__success_and_failure_content.snap
  crates/forge_domain/src/tool_result.rs
  templates/forge-partial-tool-error-reflection.hbs
Labels: type: fix

#838 feat: implement login and logout functionality
  Cargo.lock
  Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/src/agent.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/app_config.rs
  crates/forge_app/src/authenticator.rs
  crates/forge_app/src/error.rs
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/services.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/provider.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/http.rs
  crates/forge_infra/src/lib.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/info.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/app_config.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/auth.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/provider_registry.rs
  forge.yaml
Labels: type: feature

#1029 fix: stop spinner after login completion
  crates/forge_main/src/ui.rs
Labels: type: fix

#1032 fix: remove Rust toolchain update step from CI jobs and add rust-toolchain
  .github/workflows/ci.yml
  crates/forge_ci/src/jobs/build.rs
  rust-toolchain.toml
Labels: type: fix

#1034 fix: update login terminology for consistency in commands and UI messages
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
  forge.yaml
Labels: type: fix

#1049 fix: resolve login error by ensuring provider initialization in UI state
  crates/forge_main/src/ui.rs
  crates/forge_services/src/provider_registry.rs
Labels: type: fix

#1052 fix: add new line when appending
  crates/forge_services/src/tool_services/fs_patch.rs
Labels: type: feature, type: fix

#1057 fix: panic while writing app config without parent dirs
  crates/forge_infra/src/fs_write.rs
Labels: type: fix

#1058 fix: error tracing before exiting
  crates/forge_main/src/main.rs
  crates/forge_main/src/tracker.rs
Labels: type: fix

#1062 fix: remove auto compaction after each turn
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/http_config.rs
Labels: type: chore

#1063 fix: cache posthog client
  crates/forge_tracker/src/collect/posthog.rs
Labels: type: fix

#1064 fix: update default `read_timeout` to 5 minutes
  crates/forge_domain/src/http_config.rs
Labels: type: fix

#1067 fix: run chat request and compaction in parallel
  crates/forge_app/src/orch.rs
Labels: type: fix

#1070 fix: increase default connect timeout
  crates/forge_domain/src/http_config.rs
Labels: type: fix

#1071 feat(provider): implement model caching with cache-first pattern
  crates/forge_services/src/provider.rs
Labels: type: feature

#1072 chore: integrate `provider_auth_id`
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/user.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/auth.rs
  crates/forge_tracker/src/dispatch.rs
Labels: type: feature, type: chore

#1059 fix: reasoning with compaction
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/transformer/mod.rs
  crates/forge_domain/src/transformer/reasoning_normalizer.rs
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap
Labels: type: fix

#1077 chore: add GitHub label sync workflow and related tests
  .github/labels.json
  .github/workflows/labels.yml
  crates/forge_ci/src/jobs/labels.rs
  crates/forge_ci/src/jobs/mod.rs
  crates/forge_ci/src/workflow.rs
  crates/forge_ci/tests/ci.rs
Labels: type: feature

#1078 chore: add permissions to GitHub Label Sync workflow
  .github/workflows/labels.yml
  crates/forge_ci/src/jobs/labels.rs
Labels: type: chore

#1082 chore: update labels.yml
  crates/forge_ci/src/jobs/labels.rs
Labels: type: chore

#1084 chore: remove forge_domain direct dependency on crates
  Cargo.lock
  crates/forge_app/src/lib.rs
  crates/forge_app/src/truncation.rs
  crates/forge_infra/src/fs_write.rs
  crates/forge_provider/Cargo.toml
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/anthropic/request.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/anthropic/transforms/reasoning_transform.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/forge_provider/model.rs
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_provider/src/forge_provider/request.rs
  crates/forge_provider/src/forge_provider/response.rs
  crates/forge_provider/src/forge_provider/tool_choice.rs
  crates/forge_provider/src/forge_provider/transformers/drop_tool_call.rs
  crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
  crates/forge_provider/src/forge_provider/transformers/mod.rs
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  crates/forge_provider/src/forge_provider/transformers/set_cache.rs
  crates/forge_provider/src/forge_provider/transformers/tool_choice.rs
  crates/forge_provider/src/forge_provider/transformers/when_model.rs
  crates/forge_provider/src/retry.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/auth.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/discovery.rs
  crates/forge_services/src/env.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/mcp/manager.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/mcp/tool.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/provider_registry.rs
  crates/forge_services/src/tool_services/fs_patch.rs
  crates/forge_services/src/tool_services/shell.rs
  crates/forge_services/src/utils/extensions.rs
  crates/forge_services/src/workflow.rs
Labels: type: chore

#1086 fix: use `max_completion_tokens` instead of `max_tokens` for open-ai compatible providers
  crates/forge_provider/src/forge_provider/request.rs
  crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
Labels: type: fix

#1080 fix: update HTTP-Referer header to point to the new forgecode.dev URL
  crates/forge_infra/src/http.rs
Labels: type: feature, type: fix

#1027 docs: update readme for `max_requests_per_turn` and `tool_max_failure_limit`
  README.md
Labels: type: docs

#1091 feat: add mTLS support with certificate handling
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/workflow.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/provider.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/auth.rs
  crates/forge_services/src/provider.rs
Labels: type: feature

#1104 refactor: consolidate `forge_api_url` usage
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/provider.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_provider/src/forge_provider/response.rs
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/auth.rs
  crates/forge_services/src/provider_registry.rs
  forge.default.yaml
Labels: type: chore

#1107 refactor: remove mTLS certificate handling from various components
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/workflow.rs
  crates/forge_domain/src/env.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/provider.rs
Labels: type: chore

#1113 fix: regenerate binaries on publish
  .github/workflows/ci.yml
  .github/workflows/release-homebrew.yml
  .github/workflows/release-npm.yml
  Cargo.lock
  crates/forge_ci/Cargo.toml
  crates/forge_ci/src/jobs/build.rs
  crates/forge_ci/src/jobs/draft_release_update_job.rs
  crates/forge_ci/src/jobs/label_sync_job.rs
  crates/forge_ci/src/jobs/mod.rs
  crates/forge_ci/src/jobs/release_build_job.rs
  crates/forge_ci/src/jobs/release_homebrew.rs
  crates/forge_ci/src/jobs/release_npm.rs
  crates/forge_ci/src/lib.rs
  crates/forge_ci/src/matrix.rs
  crates/forge_ci/src/release_matrix.rs
  crates/forge_ci/src/workflow.rs
  crates/forge_ci/src/workflows/ci.rs
  crates/forge_ci/src/workflows/labels.rs
  crates/forge_ci/src/workflows/mod.rs
  crates/forge_ci/src/workflows/release_drafter.rs
  crates/forge_ci/src/workflows/release_homebrew.rs
  crates/forge_ci/src/workflows/release_npm.rs
  crates/forge_ci/tests/ci.rs
Labels: type: chore

#1117 fix: replace tracker error logging with tracing
  crates/forge_main/src/ui.rs
Labels: type: fix

#1118 chore: log file update stats
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_display/src/diff.rs
Labels: type: chore

#1128 refactor: consolidate inquire select functionality into select module
  crates/forge_main/src/lib.rs
  crates/forge_main/src/select.rs
  crates/forge_main/src/ui.rs
  crates/forge_main/src/update.rs
Labels: type: chore

#1139 fix: use search directory for relative paths in search results instead of CWD
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_max_output.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_output.snap
  crates/forge_app/src/snapshots/forge_app__operation__tests__fs_search_with_results.snap
  crates/forge_app/src/truncation.rs
  crates/forge_app/src/utils.rs
Labels: type: fix

#998 chore: add forge_main_neo
  Cargo.lock
  Cargo.toml
  crates/forge_main/Cargo.toml
  crates/forge_main/src/cli.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main_neo/Cargo.toml
  crates/forge_main_neo/src/domain/action.rs
  crates/forge_main_neo/src/domain/cancel.rs
  crates/forge_main_neo/src/domain/command.rs
  crates/forge_main_neo/src/domain/editor_helpers.rs
  crates/forge_main_neo/src/domain/message.rs
  crates/forge_main_neo/src/domain/mod.rs
  crates/forge_main_neo/src/domain/slash_command.rs
  crates/forge_main_neo/src/domain/spotlight.rs
  crates/forge_main_neo/src/domain/state.rs
  crates/forge_main_neo/src/domain/update.rs
  crates/forge_main_neo/src/domain/update_key_event.rs
  crates/forge_main_neo/src/domain/workspace.rs
  crates/forge_main_neo/src/entrypoint.rs
  crates/forge_main_neo/src/event_reader.rs
  crates/forge_main_neo/src/executor.rs
  crates/forge_main_neo/src/lib.rs
  crates/forge_main_neo/src/run.rs
  crates/forge_main_neo/src/widgets/app.rs
  crates/forge_main_neo/src/widgets/banner.txt
  crates/forge_main_neo/src/widgets/chat.rs
  crates/forge_main_neo/src/widgets/message_list.rs
  crates/forge_main_neo/src/widgets/mod.rs
  crates/forge_main_neo/src/widgets/spinner.rs
  crates/forge_main_neo/src/widgets/spotlight.rs
  crates/forge_main_neo/src/widgets/status_bar.rs
  crates/forge_main_neo/src/widgets/welcome.rs
  forge.yaml
  rust-analyzer.toml
Labels: type: chore

#1154 doc: update the setting name (max_tool_failure_per_turn)
  README.md
Labels: type: docs

#1157 fix: skip binary files while searching
  crates/forge_services/src/tool_services/fs_search.rs
Labels: type: fix

#1158 fix: signature is not required for summarization
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/context.rs
Labels: type: fix

#1162 fix: use ranges in file attachments
  Cargo.toml
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/attachment.rs
  crates/forge_main_neo/Cargo.toml
  crates/forge_provider/src/forge_provider/transformers/set_cache.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/range.rs
  crates/forge_services/src/tool_services/fs_read.rs
  crates/forge_services/src/utils/extensions.rs
  crates/forge_services/src/utils/mod.rs
  forge.yaml
Labels: type: feature, ratatui

#1190 fix: drop hickory dns resolver
  crates/forge_services/src/provider.rs
Labels: type: fix

#1179 fix: update token reporting logic in ForgePrompt
  crates/forge_main/src/prompt.rs
Labels: type: fix

#1187 fix: always skip searching through binary files in fs_search
  Cargo.lock
  crates/forge_fs/src/meta.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/fs_meta.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tool_services/fs_search.rs
Labels: type: fix

#1196 fix: remove reasoning tokens after compaction
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/transformer/reasoning_normalizer.rs
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap
Labels: type: feature

#1199 chore: rename provider to openai
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/lib.rs
  crates/forge_provider/src/openai/mod.rs
  crates/forge_provider/src/openai/model.rs
  crates/forge_provider/src/openai/provider.rs
  crates/forge_provider/src/openai/request.rs
  crates/forge_provider/src/openai/response.rs
  crates/forge_provider/src/openai/responses.jsonl
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_server_error.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__provider__tests__fetch_models_success.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__assistant_message_with_tool_call_conversion.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__message_with_special_chars.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_conversion.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_typescript_code.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__tool_message_with_special_chars.snap
  crates/forge_provider/src/openai/snapshots/forge_provider__openai__request__tests__user_message_conversion.snap
  crates/forge_provider/src/openai/tool_choice.rs
  crates/forge_provider/src/openai/transformers/drop_tool_call.rs
  crates/forge_provider/src/openai/transformers/make_openai_compat.rs
  crates/forge_provider/src/openai/transformers/mod.rs
  crates/forge_provider/src/openai/transformers/pipeline.rs
  crates/forge_provider/src/openai/transformers/set_cache.rs
  crates/forge_provider/src/openai/transformers/tool_choice.rs
  crates/forge_provider/src/openai/transformers/when_model.rs
  forge.yaml
Labels: type: chore

#1216 fix: drop reasoning normalizer
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/transformer/mod.rs
  crates/forge_domain/src/transformer/reasoning_normalizer.rs
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap
Labels: type: fix

#1225 fix: use custom binary file detector
  crates/forge_fs/src/binary_detection.rs
  crates/forge_fs/src/lib.rs
  crates/forge_fs/src/meta.rs
Labels: type: fix

#1231 feat: add FORGE_SUPPRESS_RETRY_ERRORS env variable to hide retry error
  crates/forge_app/src/fmt/fmt_input.rs
  crates/forge_app/src/fmt/fmt_output.rs
  crates/forge_app/src/operation.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_infra/src/env.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#1233 fix: enhance path formatting for display
  crates/forge_main/src/info.rs
Labels: type: fix

#1200 chore: add `cached_tokens` usage to tracing
  crates/forge_app/src/orch.rs
Labels: type: chore

#1250 fix: show usage information
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/user.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/src/auth.rs
Labels: type: fix

#1245 Revert "fix: drop reasoning normalizer"
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/transformer/mod.rs
  crates/forge_domain/src/transformer/reasoning_normalizer.rs
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_keeps_all_when_first_has_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_removes_all_when_first_assistant_message_has_no_reasoning.snap
  crates/forge_domain/src/transformer/snapshots/forge_domain__transformer__reasoning_normalizer__tests__reasoning_normalizer_when_no_assistant_message_present.snap
Labels: type: fix

#1254 fix: update error element to `tool_call_error` in templates
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__success_and_failure_content.snap
  crates/forge_domain/src/tool_result.rs
  templates/forge-partial-tool-required.hbs
Labels: type: fix

#1262 feat: Support for `/retry`
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#1274 fix: mcp `ToolName` sanitization
  crates/forge_domain/src/tool_name.rs
  crates/forge_services/src/mcp/service.rs
Labels: type: fix

#1276 refactor: simplify tracking logic
  crates/forge_tracker/src/can_track.rs
Labels: type: chore

#1291 fix: update tool use formatting rules to clarify JSON structure
  templates/forge-partial-tool-use-example.hbs
Labels: type: docs

#1288 fix: consolidate HTTP client implementations and use TLS configurators
  Cargo.lock
  Cargo.toml
  crates/forge_app/Cargo.toml
  crates/forge_app/src/services.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/http_config.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/http.rs
  crates/forge_provider/Cargo.toml
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/openai/mod.rs
  crates/forge_provider/src/openai/provider.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/auth.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/http.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/provider.rs
Labels: type: chore

#1292 fix: integrate JSON repair
  Cargo.lock
  Cargo.toml
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_json_repair/Cargo.toml
  crates/forge_json_repair/src/error.rs
  crates/forge_json_repair/src/lib.rs
  crates/forge_json_repair/src/parser.rs
  crates/forge_json_repair/tests/comments_unicode.rs
  crates/forge_json_repair/tests/complex_repairs.rs
  crates/forge_json_repair/tests/error_cases.rs
  crates/forge_json_repair/tests/escaping.rs
  crates/forge_json_repair/tests/numbers.rs
  crates/forge_json_repair/tests/punctuation.rs
  crates/forge_json_repair/tests/quotes.rs
  crates/forge_json_repair/tests/special_quotes.rs
  crates/forge_json_repair/tests/special_values.rs
  crates/forge_json_repair/tests/strings.rs
  crates/forge_json_repair/tests/truncation.rs
  crates/forge_json_repair/tests/valid_json.rs
Labels: type: feature, type: fix

#1284 fix: sort the models based on the names
  crates/forge_main/src/ui.rs
Labels: type: bug, type: fix

#1300 fix: use antinomy domain
  crates/forge_domain/src/provider.rs
Labels: type: fix

#1302 fix: improve error message handling
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/services.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/http.rs
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/openai/provider.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/http.rs
  crates/forge_services/src/infra.rs
Labels: type: fix

#1304 fix: parsing empty MCP configuration
  crates/forge_domain/src/mcp.rs
Labels: type: fix

#1307 fix: remove unused system time variable from template
  templates/forge-partial-system-info.hbs
Labels: type: fix
