Repository antinomyhq/forge, pull requests merged in 2025-02, with the labels that each got.

#323 fix: implement event tracking with PostHog integration
  .github/workflows/ci.yml
  Cargo.lock
  crates/forge_ci/tests/ci.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/ui.rs
  crates/forge_tracker/Cargo.toml
  crates/forge_tracker/src/can_track.rs
  crates/forge_tracker/src/collect/mod.rs
  crates/forge_tracker/src/collect/posthog.rs
  crates/forge_tracker/src/dispatch.rs
  crates/forge_tracker/src/error.rs
  crates/forge_tracker/src/event.rs
  crates/forge_tracker/src/lib.rs
Labels: type: feature

#326 chore: add Apache License 2.0 to the repository
  LICENSE
Labels: type: chore

#327 fix: use APP_VERSION constant
  crates/forge_tracker/src/dispatch.rs
Labels: type: fix

#328 fix: update download URL in install script to remove file extension
  Cargo.lock
  crates/forge_open_router/Cargo.toml
  crates/forge_tool/Cargo.toml
  install.sh
Labels: type: fix

#330 fix: optimize CI configuration and release profile settings
  .github/workflows/ci.yml
  Cargo.toml
  crates/forge_ci/tests/ci.rs
  install.sh
Labels: type: fix

#329 feat: add unrestricted shell mode and update environment handling in CLI
  README.md
  crates/forge_app/src/env.rs
  crates/forge_app/src/service/api.rs
  crates/forge_app/src/service/snapshots/forge_app__service__system_prompt__tests__tool_unsupported.snap
  crates/forge_app/src/service/system_prompt.rs
  crates/forge_app/src/service/tool_service.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/ui.rs
  crates/forge_tool/src/lib.rs
  crates/forge_tool/src/shell/executor.rs
  crates/forge_tool/src/shell/shell_tool.rs
Labels: type: feature

#331 feat: add support for more target architectures and windows os
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: feature

#332 Revert "feat: add support for more target architectures and windows os"
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: feature

#336 fix: use bundled sqlite
  Cargo.lock
  crates/forge_app/Cargo.toml
Labels: type: chore

#333 feat: add support for additional target architectures in CI configura…
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: feature

#342 chore: replace brackets with `<>`
  README.md
Labels: type: chore

#346 feat: support a pub/sub architecture for agent communication
  crates/forge_app/src/workflow.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/chat_response.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/prompt.rs
  crates/forge_domain/src/variables.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/src/ui.rs
  templates/roles/title-generator.mustache
Labels: type: fix, type: chore

#347 feat: add reset functionality to API and ExecutorService
  crates/forge_api/src/api.rs
  crates/forge_api/src/executor.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/test.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#357 fix: enhance cache setting logic in transformer pipeline
  crates/forge_open_router/src/transformers/mod.rs
Labels: type: fix

#353 fix: remove unsupported commands
  crates/forge_main/src/model.rs
Labels: type: fix

#355 feat: use success format for `/new` command
  crates/forge_display/src/title.rs
  crates/forge_main/src/ui.rs
Labels: type: feature

#361 fix(CI): update build-release job for aarch64 target
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: fix

#362 feat: set default to gnu instead of throwing an error
  install.sh
Labels: type: feature

#350 feat: read workflow from toml
  Cargo.lock
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/executor.rs
  crates/forge_api/src/lib.rs
  crates/forge_api/src/loader.rs
  crates/forge_api/src/snapshots/forge_api__loader__tests__load_workflow_with_file_prompt.snap
  crates/forge_api/src/snapshots/forge_api__loader__tests__load_workflow_with_missing_prompt_file.snap
  crates/forge_api/src/snapshots/forge_api__loader__tests__load_workflow_with_string_literals.snap
  crates/forge_api/src/snapshots/forge_api__workflow_loader__tests__load_workflow_with_file_prompt.snap
  crates/forge_api/src/snapshots/forge_api__workflow_loader__tests__load_workflow_with_missing_prompt_file.snap
  crates/forge_api/src/snapshots/forge_api__workflow_loader__tests__load_workflow_with_string_literals.snap
  crates/forge_api/src/suggestion.rs
  crates/forge_api/src/test.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/workflow.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/chat_request.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/prompt.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/file_read.rs
  crates/forge_infra/src/lib.rs
  crates/forge_infra/src/test.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/info.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/ui.rs
  crates/forge_tool/src/lib.rs
  crates/forge_tool/src/shell/shell_tool.rs
  templates/workflows/default.toml
Labels: type: feature

#348 refactor: remove unused provider and tool service modules; introduce new provider and tool traits
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/provider.rs
  crates/forge_domain/src/tool_definition.rs
  crates/forge_domain/src/tool_service.rs
Labels: type: feature, type: chore

#367 fix: preserve agent state in init method
  crates/forge_domain/src/workflow.rs
  templates/workflows/default.toml
Labels: type: fix

#387 chore(ci): add build-release-pr job for pull requests with 'build-all…
  .github/workflows/ci.yml
  crates/forge_ci/tests/ci.rs
Labels: type: chore, build-all-targets

#401 fix: rename tool from 'tool_forge_patch' to 'tool_forge_fs_patch'
  crates/forge_app/src/tools/patch/apply.rs
Labels: type: fix

#396 docs: streamline README by removing outdated API key section and enhancing feature descriptions
  README.md
Labels: type: docs

#412 docs: add Discord community section to README with invitation and badge
  README.md
Labels: type: docs

#414 refactor: Move Provider tests to forge_infra with sequential execution
  Cargo.lock
  crates/forge_domain/src/provider.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
Labels: type: chore
