Repository antinomyhq/forge, pull requests merged in 2025-06, with the labels that each got.

#883 fix: make name and command_or_url required in McpAddArgs
  crates/forge_main/src/cli.rs
  crates/forge_main/src/ui.rs
Labels: type: fix

#886 refactor(orchestrator): major rewrite with template system and integrated context compaction
  Cargo.lock
  crates/forge_api/Cargo.toml
  crates/forge_api/src/forge_api.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/api.rs
  crates/forge_domain/src/compact.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/conversation_html.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/event.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/tool.rs
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tool_definition.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_main/Cargo.toml
  crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search.snap
  crates/forge_main/src/editor.rs
  crates/forge_main/src/main.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/retry.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/mcp/manager.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/mcp/tool.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/services.rs
  crates/forge_services/src/suggestion.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/fetch.rs
  crates/forge_services/src/tools/followup.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_list.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_services/src/workflow.rs
  forge.yaml
  templates/system-prompt-engineer-act.hbs
Labels: type: chore

#893 refactor(agent): simplify context initialization and remove ephemeral field
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/context.rs
  crates/forge_domain/src/orch.rs
  crates/forge_inte/tests/test_workflow.rs
  forge.default.yaml
Labels: type: chore

#899 refactor(agent): remove unused fields and improve context compaction with template system
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/orch.rs
  crates/forge_services/src/provider.rs
  templates/partial-summary-frame.hbs
  templates/system-prompt-context-summarizer.hbs
Labels: type: chore

#901 refactor(retry): consolidate retry logic and improve error handling system
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/orch.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_infra/src/env.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/forge_provider/transformers/pipeline.rs
  crates/forge_services/src/provider.rs
Labels: type: fix

#903 feat(fs): enhance file removal UX with improved path formatting and visual feedback
  crates/forge_display/src/grep.rs
  crates/forge_main/src/prompt.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/clipper.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
Labels: type: feature, type: chore

#891 fix: handle UTF-8 character boundaries in SearchTerm processing (#888)
  crates/forge_main/src/completer/search_term.rs
  crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_chinese.snap
  crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_chinese_with_spaces.snap
  crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_emoji.snap
  crates/forge_main/src/completer/snapshots/forge_main__completer__search_term__tests__marker_based_search_mixed_chinese_english.snap
Labels: type: fix

#902 refactor: extract application layer into forge_app crate and improve reliability
  Cargo.lock
  Cargo.toml
  crates/forge_api/Cargo.toml
  crates/forge_api/src/api.rs
  crates/forge_api/src/forge_api.rs
  crates/forge_api/src/lib.rs
  crates/forge_app/Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/compaction.rs
  crates/forge_app/src/error.rs
  crates/forge_app/src/fixtures/tool_call_01.md
  crates/forge_app/src/lib.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/utils.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/retry_config.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_inte/tests/api_spec.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/discovery.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/mcp/manager.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/suggestion.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/tool_service.rs
  crates/forge_services/src/tools/fs/file_info.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/fs/fs_read.rs
  crates/forge_services/src/tools/fs/fs_remove.rs
  crates/forge_services/src/tools/fs/fs_undo.rs
  crates/forge_services/src/tools/fs/fs_write.rs
  crates/forge_services/src/tools/patch.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools/shell.rs
  crates/forge_services/src/workflow.rs
Labels: type: fix, type: chore

#911 chore: implement ToolRegistry and integrate into ForgeApp
  crates/forge_app/src/app.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_registry.rs
Labels: type: chore

#884 feat: add support for parallel tool calls for sonnet-4
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/model.rs
  crates/forge_domain/src/system_context.rs
  crates/forge_domain/src/tool_call.rs
  crates/forge_provider/src/anthropic/response.rs
  crates/forge_provider/src/forge_provider/provider.rs
  templates/partial-tool-information.hbs
Labels: type: feature

#922 chore: add tests for `ToolOutput` creation
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__follow_up_no_question.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__follow_up_with_question.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_overwrite.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_explicit_range.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_truncation_path.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_not_found.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_no_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_with_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_undo_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__net_fetch_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_success.snap
Labels: type: feature, type: chore

#924 refactor: use XML to format tool output
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__follow_up_no_question.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__follow_up_with_question.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_overwrite.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic_special_chars.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_explicit_range.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_truncation_path.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_not_found.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_undo_success.snap
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/src/shell.rs
  crates/forge_domain/src/tool_result.rs
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_asymmetric_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_boundary_no_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_large_content_with_temp_file.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_mixed_content_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_multiline_line_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_single_line_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_stderr_only_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__format_output_stdout_only_truncation.snap
  crates/forge_services/src/tools/snapshots/forge_services__tools__shell__tests__test_shell_pwd.snap
  crates/forge_services/src/tools_v2/fs_undo.rs
  crates/forge_template/src/element.rs
Labels: type: chore

#928 fix: use XML based format for attachments
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/utils.rs
  crates/forge_services/src/attachment.rs
  forge.yaml
Labels: type: fix

#919 feat: allow user to select agents interactively
  crates/forge_app/src/execution_result.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_main/src/input.rs
  crates/forge_main/src/model.rs
  crates/forge_main/src/prompt.rs
  crates/forge_main/src/state.rs
  crates/forge_main/src/ui.rs
  docs/features/operating-agents.md
  docs/features/operation-modes.md
  forge.default.yaml
  forge.yaml
Labels: type: feature

#933 refactor: use registry v2 instead of tool service
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/app.rs
Labels: type: feature

#923 refactor: add XML formatting and truncation
  crates/forge_app/src/app.rs
  crates/forge_app/src/error.rs
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/front_matter.rs
  crates/forge_app/src/lib.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_with_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__net_fetch_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__net_fetch_truncated.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_success.snap
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/truncation.rs
  crates/forge_domain/src/env.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/tools/registry.rs
  crates/forge_services/src/tools_v2/fetch.rs
  crates/forge_template/src/element.rs
Labels: type: fix, type: chore

#932 chore: drop display path from services
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_not_found.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_success.snap
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/truncation.rs
  crates/forge_app/src/utils.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/tools_v2/fs_remove.rs
  crates/forge_services/src/tools_v2/fs_search.rs
Labels: type: chore

#925 feat: add support for skipping lines in fs_search
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_max_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_no_matches.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_no_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_with_results.snap
  crates/forge_app/src/truncation.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/tools.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/tools/fs/fs_find.rs
  crates/forge_services/src/tools/registry.rs
Labels: type: feature

#935 fix: update command aliases to use intuitive names for forge and muse agents
  crates/forge_main/src/model.rs
Labels: type: fix

#940 fix: update error handling to use XML formatting for ToolOutput
  crates/forge_domain/src/snapshots/forge_domain__tool_result__tests__success_and_failure_content.snap
  crates/forge_domain/src/tool_result.rs
Labels: type: fix

#941 refactor: improve tool call context message
  Cargo.lock
  crates/forge_app/src/orch.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/tool_call_context.rs
  crates/forge_domain/src/tools.rs
  crates/forge_services/src/tools/completion.rs
  crates/forge_services/src/tools/followup.rs
  crates/forge_services/src/tools_v2/fs_create.rs
Labels: type: chore

#944 refactor: format HTML output for better readability in Element rendering
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_overwrite.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_patch_with_warning.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic_special_chars.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_explicit_range.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_truncation_path.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_remove_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_max_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_no_matches.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_no_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_with_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_undo_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__net_fetch_success.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__net_fetch_truncated.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_success.snap
  crates/forge_template/src/element.rs
Labels: type: chore

#948 refactor: move retry logic from domain to app layer for better separation of concerns
  Cargo.lock
  crates/forge_app/Cargo.toml
  crates/forge_app/src/lib.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/retry.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/retry_config.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/provider.rs
Labels: type: chore

#949 fix: interrupt for xml only when tool call is not supported
  crates/forge_app/src/orch.rs
Labels: type: fix

#950 chore: avoid sending file content back to LLM while creating file
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_overwrite.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_create_with_warning.snap
  crates/forge_fs/src/error.rs
  crates/forge_fs/src/read_range.rs
  crates/forge_services/src/tools_v2/fs_create.rs
Labels: type: chore

#942 fix: implement retryable error handling for tool call parse failures
  crates/forge_app/src/retry.rs
  crates/forge_domain/src/error.rs
  crates/forge_domain/src/result_stream_ext.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/client.rs
  crates/forge_provider/src/retry.rs
Labels: type: feature, type: fix

#953 refactor: remove unused Tool references and commented-out find method
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage_prompt_to_string.snap
  crates/forge_domain/src/tool.rs
  crates/forge_domain/src/tool_definition.rs
  crates/forge_domain/src/tool_usage.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/mcp/tool.rs
Labels: type: chore

#951 fix: write an error on fs create failure
  crates/forge_app/src/tool_registry.rs
  crates/forge_services/src/tools_v2/fs_create.rs
Labels: type: fix

#958 feat: ability to define timeout config in Env
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/input_title.rs
  crates/forge_domain/src/env.rs
  crates/forge_domain/src/http_config.rs
  crates/forge_domain/src/lib.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_provider/src/client.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/provider.rs
Labels: type: feature

#964 chore: rename tools module in services
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/tool_services/fetch.rs
  crates/forge_services/src/tool_services/followup.rs
  crates/forge_services/src/tool_services/fs_create.rs
  crates/forge_services/src/tool_services/fs_patch.rs
  crates/forge_services/src/tool_services/fs_read.rs
  crates/forge_services/src/tool_services/fs_remove.rs
  crates/forge_services/src/tool_services/fs_search.rs
  crates/forge_services/src/tool_services/fs_undo.rs
  crates/forge_services/src/tool_services/mod.rs
  crates/forge_services/src/tool_services/shell.rs
  crates/forge_services/src/tool_services/syn/lang/javascript/invalid.js
  crates/forge_services/src/tool_services/syn/lang/javascript/valid.js
  crates/forge_services/src/tool_services/syn/lang/python/invalid.py
  crates/forge_services/src/tool_services/syn/lang/python/valid.py
  crates/forge_services/src/tool_services/syn/lang/rust/invalid.rs
  crates/forge_services/src/tool_services/syn/lang/rust/valid.rs
  crates/forge_services/src/tool_services/syn/mod.rs
  crates/forge_services/src/tool_services/syn/validate.rs
Labels: type: chore

#966 chore: upgrade shell truncated output formatting
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_basic_special_chars.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_explicit_range.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_read_with_truncation_path.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_max_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_output.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__fs_search_with_results.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_both_stdout_stderr_truncation.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_empty_streams.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_exact_boundary_stdout.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_line_number_calculation.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_no_truncation.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_single_line_each.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_stderr_truncation_only.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_output_stdout_truncation_only.snap
  crates/forge_app/src/snapshots/forge_app__execution_result__tests__shell_success.snap
  crates/forge_app/src/truncation.rs
Labels: type: chore

#954 feat: implement file size limit for read operations
  Cargo.lock
  Cargo.toml
  crates/forge_app/src/execution_result.rs
  crates/forge_app/src/fmt_input.rs
  crates/forge_app/src/fmt_output.rs
  crates/forge_domain/src/env.rs
  crates/forge_fs/src/file_size.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/fs_meta.rs
  crates/forge_main/src/ui.rs
  crates/forge_services/Cargo.toml
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tool_services/fs_read.rs
  crates/forge_services/src/tool_services/fs_search.rs
  crates/forge_services/src/tool_services/fs_undo.rs
Labels: type: feature

#969 feat: add support to configure `max_tokens`
  crates/forge_app/src/orch.rs
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/lib.rs
  crates/forge_domain/src/max_tokens.rs
  crates/forge_domain/src/workflow.rs
Labels: type: feature

#968 refactor: ensure completion tool is available to all agents
  Cargo.lock
  Cargo.toml
  crates/forge_app/src/app.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_domain/Cargo.toml
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/compact.rs
  crates/forge_domain/src/max_tokens.rs
  crates/forge_domain/src/model.rs
  crates/forge_domain/src/temperature.rs
  crates/forge_domain/src/template.rs
  crates/forge_domain/src/tool_name.rs
  crates/forge_domain/src/tools.rs
  crates/forge_domain/src/top_k.rs
  crates/forge_domain/src/top_p.rs
  crates/forge_domain/src/update.rs
  crates/forge_domain/src/workflow.rs
  crates/forge_domain/tests/workflow.rs
  crates/forge_main/src/ui.rs
  crates/forge_provider/src/forge_provider/request.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/workflow.rs
  forge.default.yaml
  forge.schema.json
  forge.yaml
  workflow_schema.json
Labels: type: feature, type: chore

#971 refactor: add automatic subscription for agents
  crates/forge_domain/src/agent.rs
  crates/forge_domain/src/conversation.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/tools.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/workflow.rs
  forge.default.yaml
  workflow_schema.json
Labels: type: fix

#977 fix: log request headers for debugging purposes
  crates/forge_provider/src/forge_provider/provider.rs
Labels: type: fix

#978 feat: add logging for request headers in chat and model fetching
  crates/forge_provider/src/forge_provider/provider.rs
Labels: type: feature

#985 fix: ask for update only on 1st init
  crates/forge_main/src/ui.rs
Labels: type: fix

#980 refactor: update trait usage in services
  crates/forge_api/src/forge_api.rs
  crates/forge_app/src/agent.rs
  crates/forge_app/src/agent_executor.rs
  crates/forge_app/src/app.rs
  crates/forge_app/src/compact.rs
  crates/forge_app/src/mcp_executor.rs
  crates/forge_app/src/operation.rs
  crates/forge_app/src/orch.rs
  crates/forge_app/src/services.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_app/src/tool_registry.rs
  crates/forge_app/src/truncation.rs
  crates/forge_infra/src/env.rs
  crates/forge_infra/src/executor.rs
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/fs_create_dirs.rs
  crates/forge_infra/src/fs_meta.rs
  crates/forge_infra/src/fs_read.rs
  crates/forge_infra/src/fs_remove.rs
  crates/forge_infra/src/fs_snap.rs
  crates/forge_infra/src/fs_write.rs
  crates/forge_infra/src/inquire.rs
  crates/forge_infra/src/mcp_client.rs
  crates/forge_infra/src/mcp_server.rs
  crates/forge_services/src/attachment.rs
  crates/forge_services/src/conversation.rs
  crates/forge_services/src/discovery.rs
  crates/forge_services/src/env.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/lib.rs
  crates/forge_services/src/mcp/manager.rs
  crates/forge_services/src/mcp/service.rs
  crates/forge_services/src/mcp/tool.rs
  crates/forge_services/src/provider.rs
  crates/forge_services/src/template.rs
  crates/forge_services/src/tool_services/followup.rs
  crates/forge_services/src/tool_services/fs_create.rs
  crates/forge_services/src/tool_services/fs_patch.rs
  crates/forge_services/src/tool_services/fs_read.rs
  crates/forge_services/src/tool_services/fs_remove.rs
  crates/forge_services/src/tool_services/fs_undo.rs
  crates/forge_services/src/tool_services/shell.rs
  crates/forge_services/src/workflow.rs
Labels: type: chore

#984 fix(compaction): handle parallel tool calls in context compaction
  crates/forge_domain/src/compaction_strategy.rs
  crates/forge_domain/src/context.rs
Labels: type: fix

#972 fix: improve function call schema to work with open-ai
  crates/forge_app/src/operation.rs
  crates/forge_app/src/tool_executor.rs
  crates/forge_domain/src/snapshots/forge_domain__tool_usage__tests__tool_usage.snap
  crates/forge_domain/src/snapshots/forge_domain__tools__tests__tool_definition_json.snap
  crates/forge_domain/src/tools.rs
  crates/forge_provider/src/forge_provider/transformers/make_openai_compat.rs
Labels: type: fix

#992 chore: add more tests for can_track
  crates/forge_tracker/src/can_track.rs
Labels: type: chore

#994 refactor: migrate walker functionality to forge_infra with new abstractions
  Cargo.lock
  crates/forge_infra/Cargo.toml
  crates/forge_infra/src/forge_infra.rs
  crates/forge_infra/src/lib.rs
  crates/forge_infra/src/walker.rs
  crates/forge_services/src/discovery.rs
  crates/forge_services/src/forge_services.rs
  crates/forge_services/src/infra.rs
  crates/forge_services/src/tool_services/fs_search.rs
Labels: type: feature, type: chore

#1001 fix: update the npm update command
  README.md
  crates/forge_main/src/update.rs
Labels: type: fix

#1003 fix(ui): update init_state to handle API recreation flag
  crates/forge_main/src/ui.rs
Labels: type: fix

#1000 fix: show upstream error message on ui
  Cargo.lock
  crates/forge_provider/Cargo.toml
  crates/forge_provider/src/anthropic/provider.rs
  crates/forge_provider/src/anthropic/snapshots/forge_provider__anthropic__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/anthropic/snapshots/forge_provider__anthropic__provider__tests__fetch_models_server_error.snap
  crates/forge_provider/src/anthropic/snapshots/forge_provider__anthropic__provider__tests__fetch_models_success.snap
  crates/forge_provider/src/forge_provider/provider.rs
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__provider__tests__fetch_models_http_error_status.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__provider__tests__fetch_models_server_error.snap
  crates/forge_provider/src/forge_provider/snapshots/forge_provider__forge_provider__provider__tests__fetch_models_success.snap
  crates/forge_provider/src/lib.rs
  crates/forge_provider/src/mock_server.rs
Labels: type: fix

#1005 fix: utilise the `total_tokens` in compaction
  crates/forge_app/src/orch.rs
Labels: type: fix

#1007 fix: update README to correct JSON key for MCP servers
  README.md
Labels: type: fix
